### ISSUE TITLE
提个歌词匹配的功能增强建议

### ISSUE THREAD

**Issue by shelken** [GameBelial/ZonyLrcToolsX#100]
歌词匹配的地方我看了下，好像是默认取第一个？希望大佬加个策略：能在返回的列表中找与当前歌曲长度最接近的一条，我只看了下qq音乐的接口返回，是有个interval字段表示长度的。本人不会写C#，也不太了解；希望大佬能考虑一下加上这个功能。我的逻辑是这样，taglib读取歌曲长度；搜索歌曲列表，根据策略，如果是选择匹配最接近长度的，则比较前几条与当前歌曲长度相差值，取最小绝对值的id，再根据songid去下歌词。

**Comment by real-zony** [comment]
Resolved.
