### ISSUE TITLE
error: 50010

### ISSUE THREAD

**Issue by lemonsiny2016** [GameBelial/ZonyLrcToolsX#101]
Can't download the lyrics:

2022-06-09 10:05:37.007 +01:00 [WRN] 错误代码: 50010，信息: Http 请求的结果反序列化为 Json 失败。

**Comment by real-zony** [comment]
@lemonsiny2016 有对应的错误歌曲名称吗？

**Comment by ballballu** [comment]
也是同样的问题，对于日文歌曲都会显示这个报错
![image](https://user-images.githubusercontent.com/45290612/177549369-e0433f22-9e8a-4ede-944c-34cab9a91e92.png)

**Comment by real-zony** [comment]
@ballballu 最新版本是可以正常下载该歌曲的。
![image](https://user-images.githubusercontent.com/3907132/191684106-c1dd7475-0a94-46ce-9a7f-9bb6950902ac.png)
