### ISSUE TITLE
请问macos需要安装.net么？

### ISSUE THREAD

**Issue by fateavalon** [GameBelial/ZonyLrcToolsX#104]

**Comment by real-zony** [comment]
不需要，直接下载二进制文件运行即可。

**Comment by fateavalon** [comment]
谢谢 似乎m1不能运行?
Permission denied, sudo 也不行

还有请问是不是国外只能挂代理翻回去才能用？

**Comment by real-zony** [comment]
因为我是 X86 的机器，M1 机器的话还没编译 ARM 版本的可执行文件。后续会考虑支持。如果在国外的话，需要代理回去才能用，网易云那边做了限制。

**Comment by fateavalon** [comment]
谢谢！
