### ISSUE TITLE
Win10下在win64位版本，无法正常打开软件

### ISSUE THREAD

**Issue by cedricxd** [GameBelial/ZonyLrcToolsX#108]
Win10下在win64位版本，无法正常打开软件，命令行窗口一闪即逝。

**Comment by lyhlead** [comment]
用cmd打开文件夹，用命令行执行exe文件，exe文件无法双击打开

**Comment by wxiyangqq** [comment]
不好意思，没有电脑基础不会使用啊，有没有像上一个版本那样可以直接打开的啊 ！谢谢 ，或者有没有使用说明，非常感谢

**Comment by cedricxd** [comment]
> 用cmd打开文件夹，用命令行执行exe文件，exe文件无法双击打开

原来如此，多谢解释
