### ISSUE TITLE
下载使用帮助

### ISSUE THREAD

**Issue by maNickFry** [GameBelial/ZonyLrcToolsX#109]
![Uploading 微信截图_20220805124138.png…]()
怎么扫描目录和下载歌词呢，按照help 用ZonyLrcTools.exe加路径加-d 后提示Specify --help for a list of available options and commands.

**Comment by real-zony** [comment]
有子命令的，下载的子命令是 download，完整的应该是：
```shell
./ZonyLrcTools.Cli.exe download -d "C:\歌曲目录" -l -n 2
```

**Comment by real-zony** [comment]
长时间没有回复，关闭 Issue，如果有任何疑问可以重新打开。
