### ISSUE TITLE
为什么ZonyLrcToolsX_Alpha.2022072501_win-x64，exe运行不了？直接退出了。微信nlanguage

### ISSUE THREAD

**Issue by nissansz** [GameBelial/ZonyLrcToolsX#113]
为什么ZonyLrcToolsX_Alpha.2022072501_win-x64，exe运行不了？直接退出了。微信nlanguage

**Comment by real-zony** [comment]
@nissansz 请参考 README.md ，先打开命令行然后键入命令运行，如果还是不清楚，可以添加 QQ 群 337656932 里面有视频教程。
