### ISSUE TITLE
错误码50005

### ISSUE THREAD

**Issue by Necream** [GameBelial/ZonyLrcToolsX#116]
![image](https://user-images.githubusercontent.com/99577760/192007350-2ae31ccc-ae5c-4795-8adb-07200a74b4e1.png)

**Comment by Necream** [comment]
-a -n 2

**Comment by real-zony** [comment]
@Lisu-Liso 使用的是网易云音乐？有歌曲信息吗？

**Comment by Necream** [comment]
呃，这个问题已经解决了，重新下载了一个版本

**Comment by MasterLover** [comment]
> 呃，这个问题已经解决了，重新下载了一个版本

所以怎么解决的

**Comment by stop-bullshit** [comment]
![image](https://user-images.githubusercontent.com/25337521/196087569-025c5961-9625-41ad-8d0d-2774863b1b56.png)
刚开始好好地然后就挂了，看着像频繁请求导致的，
下面是warn日志，error日志没有
```
2022-10-17 12:09:10.219 +08:00 [WRN] 错误代码: 50005，信息: 下载请求的返回值不合法，可能是服务端故障。
附加信息:
 null
```

**Comment by real-zony** [comment]
@MasterLover 你使用的是最新的 Release 版本吗?

**Comment by stop-bullshit** [comment]
> @MasterLover 你使用的是最新的 Release 版本吗?

是的 使用的最新版本

**Comment by real-zony** [comment]
@MasterLover 对应的歌词文件有生成吗？如果有报错的话，现有逻辑会使用其他下载器继续进行下载操作。

**Comment by stop-bullshit** [comment]
> @MasterLover 对应的歌词文件有生成吗？如果有报错的话，现有逻辑会使用其他下载器继续进行下载操作。

您好，我看了下 歌词文件生成成功了  只是界面有这个警告。error日志文件里面没有输出   目前不影响使用，感谢回复
