### ISSUE TITLE
显示下载成功但没有找到文件

### ISSUE THREAD

**Issue by Alex6357** [GameBelial/ZonyLrcToolsX#117]
执行`./ZonyLrcTools.Cli.exe download -d "文件夹" -l -n 2`之后显示下载成功但是扫遍全盘都找不到下载的文件

**Comment by Alex6357** [comment]
重新尝试了一下，似乎只有支持自动滚动的歌词才会被正确保存

**Comment by real-zony** [comment]
@Alex6357  能否提供无法正常下载的歌曲文件？一首就行。

**Comment by Alex6357** [comment]
[陈致逸,HOYO-MiX - Genshin Impact Main Theme 原神.zip](https://github.com/real-zony/ZonyLrcToolsX/files/9875791/HOYO-MiX.-.Genshin.Impact.Main.Theme.zip)
后缀为flac
很有可能是这种“歌词”根本没有时间标志，只是纯粹的txt

**Comment by real-zony** [comment]
确实是，这种目前会认为是纯音乐，不会写入歌词文件。
```
作曲 : 陈致逸 Yu-Peng Chen(HOYO-MiX)
指挥 Conductor:Robert Ziegler
乐队 Orchestra:伦敦爱乐乐团 London Philharmonic Orchestra
录音棚 Recording Studio:Air Studios
录音师 Recording Engineer:Nick Wollage
工程师 ProTools Operator:Laurence Anslow
混音 Mixing Engineer:Nick Wollage
母带 Mastering Engineer:John Webber
出品 Produced by:HOYO-MiX
```
