### ISSUE TITLE
想提一个功能，既然可以获取到tag，为什么不直接把tag写入音乐文件呢？

### ISSUE THREAD

**Issue by l0rraine** [GameBelial/ZonyLrcToolsX#119]
光有歌词并不能在播放器上完美播放，看着未知很难受

**Comment by real-zony** [comment]
@l0rraine 默认 Tag 就是从音乐文件获取的，如果获取不到就会从歌曲文件的名称进行解析。

如果你想要的功能是基于歌曲文件名，将歌手/歌名写入到歌曲文件的 Tag 信息里面，使用专业的软件，比如 MP3Tag 可以解决你这个需求。
