### ISSUE TITLE
希望能修正在windows下，最后的路径符“\”能否也能被识别？

### ISSUE THREAD

**Issue by kimycai** [GameBelial/ZonyLrcToolsX#127]
例如我有这样一条命令：
ZonyLrcTools.Cli download -d "Z:\Music\苏慧伦\甜蜜心事\" -l 
会显示“The directory 'Z:\Music\苏慧伦\甜蜜心事" -l ' does not exist.”
但如果把最后的”\“去掉，则命令能正常运行，所以能否让命令也能识别“\”，
即“Z:\Music\苏慧伦\甜蜜心事”=“Z:\Music\苏慧伦\甜蜜心事\” 呢?

**Comment by real-zony** [comment]
根据文件路径的语义来说，如果路径末尾有 '\' 说明你指定的是在 **甜蜜心事** 目录里面的某个文件夹，是一个不完整的路径。

**Comment by kimycai** [comment]
> 根据文件路径的语义来说，如果路径末尾有 '' 说明你指定的是在 **甜蜜心事** 目录里面的某个文件夹，是一个不完整的路径。

嗯，似乎你说的逻辑是对的，O(∩_∩)O

**Comment by KiyanYang** [comment]
感觉应该是转义问题

试试 `ZonyLrcTools.Cli download -d "Z:\Music\苏慧伦\甜蜜心事\\" -l`
