### ISSUE TITLE
开启 isSkipExistLyricFiles 功能的bug

### ISSUE THREAD

**Issue by yuuuuukiu** [GameBelial/ZonyLrcToolsX#129]
在config中开启isSkipExistLyricFiles功能后无法操作所有命令
![image](https://user-images.githubusercontent.com/88711461/221408814-c69b6142-5cf4-4473-918b-8a2762719cd3.png)
![image](https://user-images.githubusercontent.com/88711461/221408880-24d1abe6-f7bb-48fa-b2b1-698adba88010.png)
p2为打开isSkipExistLyricFiles功能输入命令后无任何回应
![image](https://user-images.githubusercontent.com/88711461/221408924-664cd964-16b3-42ed-a967-7d820ad83e7e.png)
无任何错误与警告

**Comment by real-zony** [comment]
@KemurihinoGatsu  单词打错了，应该是 `true`。

**Comment by yuuuuukiu** [comment]
我去，我是伞兵（
