### ISSUE TITLE
歌词时间轴格式不一致导致 Walkman 无法正常显式歌词

### ISSUE THREAD

**Issue by YunhaoJiang** [GameBelial/ZonyLrcToolsX#13]
************** 异常文本 **************
System.ArgumentNullException: 值不能为 null。
参数名: 源歌词文本数据为空，请传入有效文本。
   在 Zony.Lib.Infrastructures.Lyrics.LyricItemCollection..ctor(String srcLyricText)
   在 Zony.Lib.NetEase.Startup.DownLoad(String songName, String artistName, Byte[]& data)
   在 ZonyLrcTools.Events.LyricDownLoadEvent.<>c__DisplayClass3_0.<HandleEvent>b__1(MusicInfoModel info, ParallelLoopState loopState)
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvoke()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

**Comment by GameBelial** [comment]
该问题已经修复了...请尝试[ Release 最新版本](https://github.com/GameBelial/ZonyLrcToolsX/releases/tag/0.1.9.3-201812092233).

**Comment by YunhaoJiang** [comment]
@GameBelial 似乎还有些问题...
************** 异常文本 **************
System.ArgumentException: Could not cast or convert from System.String to Zony.Lib.Net.JsonModels.NetEase.NetEaseInnerResultModel.
   在 Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   在 Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)

**Comment by YunhaoJiang** [comment]
@GameBelial
下任何歌曲的时候都有这个问题

**Comment by GameBelial** [comment]
@YunhaoJiang 能够随便上传一首有问题的歌曲么，我这边好做测试。

**Comment by YunhaoJiang** [comment]
> @YunhaoJiang 能够随便上传一首有问题的歌曲么，我这边好做测试。

@GameBelial 不知是否我这里的问题 所有歌曲似乎都无法下载歌词
链接: https://pan.baidu.com/s/1m3alpQpPnTesq-xdM3ZZEw 提取码: fidj

**Comment by YunhaoJiang** [comment]
> @YunhaoJiang 能够随便上传一首有问题的歌曲么，我这边好做测试。

已经通过重启解决 但似乎文件输出上有问题 输出的文件无法被Walkman读取 不管将里面的歌词改成什么样 但如果自己通过txt写歌词如`[00:00:00]test`就可以显示 而软件输出的不行

**Comment by GameBelial** [comment]
@YunhaoJiang 是因为软件输出的格式为 [00:00.00] 的原因么？

**Comment by YunhaoJiang** [comment]
> @YunhaoJiang 是因为软件输出的格式为 [00:00.00] 的原因么？

我测试了一下 不单单是这样 还有开头少0的问题
软件输出的全部都是`[1:59.59]`  这种`[X:XX.XX]`格式
将其全部替换为`[01:59:59]`这种`[XX:XX:XX]`格式即可正常显示
望修复 谢谢！

**Comment by GameBelial** [comment]
OK，了解了，我今天抽时间看一下。

**Comment by YunhaoJiang** [comment]
> OK，了解了，我今天抽时间看一下。

好的 麻烦了

**Comment by GameBelial** [comment]
@YunhaoJiang 你尝试一下这个版本呢，看是否能够解决你的问题。
[ZonyLrcToolsX 0.1.9.3-201812112154.zip](https://github.com/GameBelial/ZonyLrcToolsX/files/2667837/ZonyLrcToolsX.0.1.9.3-201812112154.zip)

**Comment by YunhaoJiang** [comment]
> @YunhaoJiang 你尝试一下这个版本呢，看是否能够解决你的问题。
> [ZonyLrcToolsX 0.1.9.3-201812112154.zip](https://github.com/GameBelial/ZonyLrcToolsX/files/2667837/ZonyLrcToolsX.0.1.9.3-201812112154.zip)

嗯嗯 看起来已经解决了

**Comment by YunhaoJiang** [comment]
> @YunhaoJiang 你尝试一下这个版本呢，看是否能够解决你的问题。
> [ZonyLrcToolsX 0.1.9.3-201812112154.zip](https://github.com/GameBelial/ZonyLrcToolsX/files/2667837/ZonyLrcToolsX.0.1.9.3-201812112154.zip)

经过批量测试 已经可以正常显示 非常感谢！

**Comment by SGREYCN** [comment]
好像最新的ZonyLrcToolsX.0.1.9.3-201812092233这个版本时间轴格式又变回X:XX:XX了
