### ISSUE TITLE
外文歌曲名会显示为乱码，然后报错index out of range

### ISSUE THREAD

**Issue by HuanzhiMao** [GameBelial/ZonyLrcToolsX#133]
版本Alpha.2023010456  
当歌曲名或歌手包含除了中文和英文之外的字符的时候(比如韩文或者日文)，会显示为？，然后报index out of range的错。
另外，有时候歌曲名和歌手都是中文的时候，也会有index out of range的问题；在这种情况下歌曲名和歌手的信息都是正确提取的。
![image](https://user-images.githubusercontent.com/93459410/227667233-c0521d0d-d2d1-40af-b126-75af8b5b4df5.png)
![image](https://user-images.githubusercontent.com/93459410/227667241-5c8c63fe-e29a-4a0d-bb35-b8005e3892cc.png)
![image](https://user-images.githubusercontent.com/93459410/227667258-356dd6a8-203d-4a68-8a4c-512c810af2cb.png)

这是我的config
![image](https://user-images.githubusercontent.com/93459410/227667761-103873c3-9083-4b84-8d38-92c90fdb9262.png)
谢谢，辛苦了

**Comment by real-zony** [comment]
@HuanzhiMao 能够打包上传一两首乱码的歌曲吗？

**Comment by HuanzhiMao** [comment]
文件有些大，我放到google drive上了。https://drive.google.com/file/d/1X_kqVIy6uQ1R3gou83lgBoNOWjot5Eon/view?usp=share_link

**Comment by real-zony** [comment]
@HuanzhiMao  最新版本无法复现该问题。
![image](https://user-images.githubusercontent.com/3907132/228266530-5338b1e5-d32e-4854-ba6e-6cef981290df.png)

**Comment by real-zony** [comment]
![image](https://user-images.githubusercontent.com/3907132/228266671-24635dc4-81e7-48bb-b35f-87d7158a0234.png)

**Comment by real-zony** [comment]
最新版本可以这里找到: https://github.com/real-zony/ZonyLrcToolsX/actions/runs/4544366455，往下面拉可以看到产物，下载下来里面文件会有对应的编译好的二进制文件。

**Comment by LeonhardtHUST** [comment]
inedx out of range 复现
![image](https://user-images.githubusercontent.com/92073072/229325538-076b9a33-c3a6-4abf-8554-9020a7105981.png)

**Comment by real-zony** [comment]
该问题在最新版本已经修复，问题是由于酷狗音乐下载器没有正确处理没有找到歌曲的清空。
