### ISSUE TITLE
不会使用，打不开

### ISSUE THREAD

**Issue by gufangy** [GameBelial/ZonyLrcToolsX#137]
为什么点击exe代码弹出后自动关闭无法使用，win11系统

**Comment by real-zony** [comment]
@gufangy 参考使用说明，打开命令提示符/POWERSHELL/终端使用，群文件里面有使用视频。

**Comment by gufangy** [comment]
群号是多少，在哪里看

**Comment by real-zony** [comment]
@gufangy QQ 群: 337656932，群文件有。
