### ISSUE TITLE
在部分歌曲下载未成功时没有正确报错

### ISSUE THREAD

**Issue by XBatteria** [GameBelial/ZonyLrcToolsX#138]
版本2023041664
下载如下歌曲
![Snipaste_2023-05-10_00-57-22](https://github.com/real-zony/ZonyLrcToolsX/assets/59811644/5dd6d101-aecc-4e17-93d5-4499864220a5)
显示全部歌曲下载成功成功，但实际只下载到一部分
![image](https://github.com/real-zony/ZonyLrcToolsX/assets/59811644/25574490-495c-40f4-a6d9-ba3bf34ee0ad)
歌词下载失败列表也只有表头，没有内容

另外，截图中下载到的歌词比我稍早前几个小时下载到的要少一些，当时除了这个版本还用2023032862下载过，不清楚是否有关系
之后测试到0416下载到10首，0328下载到6首（软件提示成功8首），其中有一首是0328下载到而0416没有下载到的（1.05）
然而之前下载到15/18首，仅缺失01、15、16

之后试图从歌单下载但是二维码扫不出，字体问题？
![image](https://github.com/real-zony/ZonyLrcToolsX/assets/59811644/0c9bca4b-296f-4a59-b11b-8046126b5a5f)

**Comment by real-zony** [comment]
没有下载到歌词的是否为纯音乐？因为纯音乐的会被视为成功。

**Comment by XBatteria** [comment]
确认过了，平台上对应歌曲都是有歌词的，但问题姑且解决了。
后来发现问题主要是因为metadata和平台上的不对应，有的曲子有相同曲名的纯音乐，有的曲子是，在平台上版本的曲名大小写与我本地版本标签上的不一致，而又有没有标注歌词的翻唱版本和标签的大小写是一致的。总而言之，全部按照平台上的版本修改标签后都能正常下载。
那么，是否可以在下载过程中遇到纯音乐时进行相应的标注（如：纯音乐，已跳过）？或是在标签中歌手无法与平台上任一结果对应时可以进行选择来避免这些情况？
感谢您的工作。

**Comment by real-zony** [comment]
已处理
