### ISSUE TITLE
.NET 报错

### ISSUE THREAD

**Issue by swang93** [GameBelial/ZonyLrcToolsX#15]
<code>
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Could not cast or convert from System.String to Zony.Lib.Net.JsonModels.NetEase.NetEaseInnerResultModel.
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3260.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
ZonyLrcTools
    Assembly Version: 0.1.9.3
    Win32 Version: 0.1.9.3
    CodeBase: file:///C:/Users/wangs/Desktop/ZonyLrcToolsX.0.1.9.3-201812092233/ZonyLrcTools.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3260.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Zony.Lib.Infrastructures
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Users/wangs/Desktop/ZonyLrcToolsX.0.1.9.3-201812092233/Zony.Lib.Infrastructures.DLL
----------------------------------------
Castle.Windsor
    Assembly Version: 4.0.0.0
    Win32 Version: 4.1.1
    CodeBase: file:///C:/Users/wangs/Desktop/ZonyLrcToolsX.0.1.9.3-201812092233/Castle.Windsor.DLL
----------------------------------------
Castle.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.3.1
    CodeBase: file:///C:/Users/wangs/Desktop/ZonyLrcToolsX.0.1.9.3-201812092233/Castle.Core.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3260.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.3260.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Zony.Lib.Plugin
    Assembly Version: 1.3.1.0
    Win32 Version: 1.3.1.0
    CodeBase: file:///C:/Users/wangs/Desktop/ZonyLrcToolsX.0.1.9.3-201812092233/Zony.Lib.Plugin.DLL
----------------------------------------
Zony.Lib.UIComponents
    Assembly Version: 1.0.1.0
    Win32 Version: 1.0.1.0
    CodeBase: file:///C:/Users/wangs/Desktop/ZonyLrcToolsX.0.1.9.3-201812092233/Zony.Lib.UIComponents.DLL
----------------------------------------
log4net
    Assembly Version: 2.0.8.0
    Win32 Version: 2.0.8.0
    CodeBase: file:///C:/Users/wangs/Desktop/ZonyLrcToolsX.0.1.9.3-201812092233/log4net.DLL
----------------------------------------
taglib-sharp
    Assembly Version: 2.1.0.0
    Win32 Version: 2.1.0.0
    CodeBase: file:///C:/Users/wangs/Desktop/ZonyLrcToolsX.0.1.9.3-201812092233/Plugins/taglib-sharp.dll
----------------------------------------
Zony.Lib.AlbumDownLoad
    Assembly Version: 1.1.1.1
    Win32 Version: 1.1.1.1
    CodeBase: file:///C:/Users/wangs/Desktop/ZonyLrcToolsX.0.1.9.3-201812092233/Plugins/Zony.Lib.AlbumDownLoad.dll
----------------------------------------
Zony.Lib.AlbumImgExport
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Users/wangs/Desktop/ZonyLrcToolsX.0.1.9.3-201812092233/Plugins/Zony.Lib.AlbumImgExport.dll
----------------------------------------
Zony.Lib.MusicInfoEdit
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/wangs/Desktop/ZonyLrcToolsX.0.1.9.3-201812092233/Plugins/Zony.Lib.MusicInfoEdit.dll
----------------------------------------
Zony.Lib.NCMConverter
    Assembly Version: 0.0.0.1
    Win32 Version: 0.0.0.1
    CodeBase: file:///C:/Users/wangs/Desktop/ZonyLrcToolsX.0.1.9.3-201812092233/Plugins/Zony.Lib.NCMConverter.dll
----------------------------------------
Zony.Lib.NetEase
    Assembly Version: 2.2.1.0
    Win32 Version: 2.2.1.0
    CodeBase: file:///C:/Users/wangs/Desktop/ZonyLrcToolsX.0.1.9.3-201812092233/Plugins/Zony.Lib.NetEase.dll
----------------------------------------
Zony.Lib.SongListDownload
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Users/wangs/Desktop/ZonyLrcToolsX.0.1.9.3-201812092233/Plugins/Zony.Lib.SongListDownload.dll
----------------------------------------
Zony.Lib.TagLib
    Assembly Version: 1.2.3.0
    Win32 Version: 1.2.3.0
    CodeBase: file:///C:/Users/wangs/Desktop/ZonyLrcToolsX.0.1.9.3-201812092233/Plugins/Zony.Lib.TagLib.dll
----------------------------------------
Zony.Lib.Net
    Assembly Version: 1.2.2.0
    Win32 Version: 1.2.2.0
    CodeBase: file:///C:/Users/wangs/Desktop/ZonyLrcToolsX.0.1.9.3-201812092233/Zony.Lib.Net.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.1.22727
    CodeBase: file:///C:/Users/wangs/Desktop/ZonyLrcToolsX.0.1.9.3-201812092233/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3260.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3260.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

</code>

![1](https://user-images.githubusercontent.com/42833304/50064324-26c93500-0176-11e9-98cc-db57fc85bdaa.png)

**Comment by GameBelial** [comment]
了解，我这边抽时间看一下。

**Comment by GameBelial** [comment]
已经长时间没有反馈，将问题关闭，如果有任何疑问请再次打开。

**Comment by Baka943-0v0** [comment]
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Zony.Lib.NetEase.Startup.GetLyricJsonObject(Object postParam)
   在 Zony.Lib.NetEase.Startup.DownLoad(String songName, String artistName, Byte[]& data)
   在 ZonyLrcTools.Events.LyricDownLoadEvent.<>c__DisplayClass3_0.<HandleEvent>b__1(MusicInfoModel info, ParallelLoopState loopState)
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvoke()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )


************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.7.3324.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
ZonyLrcTools
    程序集版本:0.1.9.1
    Win32 版本:0.1.9.1
    基本代码:file:///H:/TOOLS/lyrics%20matcher/ZonyLrcTools.exe
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.7.3324.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.7.3353.0 built by: NET472REL1LAST_B
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.7.3190.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Zony.Lib.Infrastructures
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///H:/TOOLS/lyrics%20matcher/Zony.Lib.Infrastructures.DLL
----------------------------------------
Castle.Windsor
    程序集版本:4.0.0.0
    Win32 版本:4.1.1
    基本代码:file:///H:/TOOLS/lyrics%20matcher/Castle.Windsor.DLL
----------------------------------------
Castle.Core
    程序集版本:4.0.0.0
    Win32 版本:4.3.1
    基本代码:file:///H:/TOOLS/lyrics%20matcher/Castle.Core.DLL
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.7.3324.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.7.3324.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.7.3190.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    程序集版本:0.0.0.0
    Win32 版本:4.7.3324.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Zony.Lib.Plugin
    程序集版本:1.3.1.0
    Win32 版本:1.3.1.0
    基本代码:file:///H:/TOOLS/lyrics%20matcher/Zony.Lib.Plugin.DLL
----------------------------------------
Zony.Lib.UIComponents
    程序集版本:1.0.1.0
    Win32 版本:1.0.1.0
    基本代码:file:///H:/TOOLS/lyrics%20matcher/Zony.Lib.UIComponents.DLL
----------------------------------------
taglib-sharp
    程序集版本:2.1.0.0
    Win32 版本:2.1.0.0
    基本代码:file:///H:/TOOLS/lyrics%20matcher/Plugins/taglib-sharp.dll
----------------------------------------
Zony.Lib.AlbumDownLoad
    程序集版本:1.1.1.1
    Win32 版本:1.1.1.1
    基本代码:file:///H:/TOOLS/lyrics%20matcher/Plugins/Zony.Lib.AlbumDownLoad.dll
----------------------------------------
Zony.Lib.AlbumImgExport
    程序集版本:1.1.0.0
    Win32 版本:1.1.0.0
    基本代码:file:///H:/TOOLS/lyrics%20matcher/Plugins/Zony.Lib.AlbumImgExport.dll
----------------------------------------
Zony.Lib.NetEase
    程序集版本:2.2.0.0
    Win32 版本:2.2.0.0
    基本代码:file:///H:/TOOLS/lyrics%20matcher/Plugins/Zony.Lib.NetEase.dll
----------------------------------------
Zony.Lib.SongListDownload
    程序集版本:1.1.0.0
    Win32 版本:1.1.0.0
    基本代码:file:///H:/TOOLS/lyrics%20matcher/Plugins/Zony.Lib.SongListDownload.dll
----------------------------------------
Zony.Lib.TagLib
    程序集版本:1.2.3.0
    Win32 版本:1.2.3.0
    基本代码:file:///H:/TOOLS/lyrics%20matcher/Plugins/Zony.Lib.TagLib.dll
----------------------------------------
Zony.Lib.Net
    程序集版本:1.2.2.0
    Win32 版本:1.2.2.0
    基本代码:file:///H:/TOOLS/lyrics%20matcher/Zony.Lib.Net.DLL
----------------------------------------
System.Net.Http
    程序集版本:4.0.0.0
    Win32 版本:4.7.3190.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Newtonsoft.Json
    程序集版本:12.0.0.0
    Win32 版本:12.0.1.22727
    基本代码:file:///H:/TOOLS/lyrics%20matcher/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    程序集版本:4.0.0.0
    Win32 版本:4.7.3190.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    程序集版本:4.0.0.0
    Win32 版本:4.7.3324.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    程序集版本:4.0.0.0
    Win32 版本:4.7.3260.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
log4net
    程序集版本:2.0.8.0
    Win32 版本:2.0.8.0
    基本代码:file:///H:/TOOLS/lyrics%20matcher/log4net.DLL
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.7.3190.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Web
    程序集版本:4.0.0.0
    Win32 版本:4.7.3282.0 built by: NET472REL1LAST_B
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.7.3190.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。
