### ISSUE TITLE
使用代理失败

### ISSUE THREAD

**Issue by SimpleCavaliers** [GameBelial/ZonyLrcToolsX#152]
<img width="757" alt="1" src="https://github.com/user-attachments/assets/92502ae1-9d2b-489d-9c01-077c79f2dc8a">
<img width="661" alt="2" src="https://github.com/user-attachments/assets/c57b57a2-0078-4290-9941-8672eb6f1767">
<img width="347" alt="3" src="https://github.com/user-attachments/assets/c3a4177c-d8c8-4403-9557-b395a21f4f5d">

使用代理失败，但是请求其它网站是成功的，如图3。

**Comment by real-zony** [comment]
目前软件仅支持 http 代理。
