### ISSUE TITLE
歌词完全不可用

### ISSUE THREAD

**Issue by KiryChanOfficial** [GameBelial/ZonyLrcToolsX#156]
歌词与歌曲不匹配，使用CSV时出现乱码，多次测试时同一首歌曲匹配的LRC也不一定相同（同时也都是错的）

**Comment by real-zony** [comment]
能否提供 csv 文件？

**Comment by KiryChanOfficial** [comment]
[a.csv](https://github.com/user-attachments/files/18052303/a.csv)

使用的命令：
```
.\ZonyLrcTools.Cli.exe download -sc csv -o "X:\TempFiles" -f "X:\a.csv" -l
```

**Comment by real-zony** [comment]
乱码问题导致的歌曲信息识别问题，该原因是由于 csv 文件编码为 gb2312 导致，默认程序是以 utf-8 读取 csv 文件的，所以乱码，该问题已经修复。
