### ISSUE TITLE
If you don't know Chinese, it's impossible to find the English documentation

### ISSUE THREAD

**Issue by ClaireCJS** [GameBelial/ZonyLrcToolsX#157]
Seriously. I've tried. Github redirects to your website, which has no way to find anything in English on.

Where are the detailed  usage instructions?

**Comment by real-zony** [comment]
Thank you for your attention. The English documentation is not yet complete, and I will take some time to finish this part of the documentation.

**Comment by ranxianglei** [comment]
You can use google translate，it‘s great @ClaireCJS

**Comment by ClaireCJS** [comment]
> You can use google translate，it‘s great @ClaireCJS

One wrong translation could cost time. I had a project to work on. I moved on and used lyricsGenius instead.

**Comment by ranxianglei** [comment]
吹毛求疵
