### ISSUE TITLE
哥，极少部分音乐下载时...

### ISSUE THREAD

**Issue by longzho** [GameBelial/ZonyLrcToolsX#158]
![被误识别为纯音乐](https://github.com/user-attachments/assets/7fc36fcb-2d27-463f-a082-4a0169f08b4c)
以下为音乐原地址：https://music.163.com/#/song?id=1318101671
这是首有歌词的歌，但是在提示下载成功后却发现被识别成了纯音乐ಥ_ಥ

**Comment by real-zony** [comment]
最新版本已经修复了该问题，如果还有该问题请重新打开这个 Issue。
