### ISSUE TITLE
下载歌词程序报错：应用程序中发生了未经处理的异常

### ISSUE THREAD

**Issue by ligan92** [GameBelial/ZonyLrcToolsX#16]
下载Panda Eyes - Fuck Off纯音乐歌词时报错

ZonyLrcTools X-Version：0.1.9.3X
应用程序中发生了未经处理的异常。如果单击“继续”，应用程序将忽略此错误并尝试继续。如果单击“退出”，应用程序将立即关闭。
未将对象引用设置到对象的实例。。

详细信息：

有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Zony.Lib.NetEase.Startup.GetLyricJsonObject(Object postParam)
   在 Zony.Lib.NetEase.Startup.DownLoad(String songName, String artistName, Byte[]& data)
   在 ZonyLrcTools.Events.LyricDownLoadEvent.<>c__DisplayClass3_0.<HandleEvent>b__1(MusicInfoModel info, ParallelLoopState loopState)
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvoke()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.7.3260.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
ZonyLrcTools
    程序集版本:0.1.9.3
    Win32 版本:0.1.9.3
    基本代码:file:///C:/Users/damie/AppData/Local/Temp/Rar$EXa14036.18281/ZonyLrcTools.exe
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.7.3221.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.7.3190.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Zony.Lib.Infrastructures
    程序集版本:1.1.0.0
    Win32 版本:1.1.0.0
    基本代码:file:///C:/Users/damie/AppData/Local/Temp/Rar$EXa14036.18281/Zony.Lib.Infrastructures.DLL
----------------------------------------
Castle.Windsor
    程序集版本:4.0.0.0
    Win32 版本:4.1.1
    基本代码:file:///C:/Users/damie/AppData/Local/Temp/Rar$EXa14036.18281/Castle.Windsor.DLL
----------------------------------------
Castle.Core
    程序集版本:4.0.0.0
    Win32 版本:4.3.1
    基本代码:file:///C:/Users/damie/AppData/Local/Temp/Rar$EXa14036.18281/Castle.Core.DLL
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.7.3221.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    程序集版本:0.0.0.0
    Win32 版本:4.7.3260.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Zony.Lib.Plugin
    程序集版本:1.3.1.0
    Win32 版本:1.3.1.0
    基本代码:file:///C:/Users/damie/AppData/Local/Temp/Rar$EXa14036.18281/Zony.Lib.Plugin.DLL
----------------------------------------
Zony.Lib.UIComponents
    程序集版本:1.0.1.0
    Win32 版本:1.0.1.0
    基本代码:file:///C:/Users/damie/AppData/Local/Temp/Rar$EXa14036.18281/Zony.Lib.UIComponents.DLL
----------------------------------------
log4net
    程序集版本:2.0.8.0
    Win32 版本:2.0.8.0
    基本代码:file:///C:/Users/damie/AppData/Local/Temp/Rar$EXa14036.18281/log4net.DLL
----------------------------------------
taglib-sharp
    程序集版本:2.1.0.0
    Win32 版本:2.1.0.0
    基本代码:file:///C:/Users/damie/AppData/Local/Temp/Rar$EXa14036.18281/Plugins/taglib-sharp.dll
----------------------------------------
Zony.Lib.AlbumDownLoad
    程序集版本:1.1.1.1
    Win32 版本:1.1.1.1
    基本代码:file:///C:/Users/damie/AppData/Local/Temp/Rar$EXa14036.18281/Plugins/Zony.Lib.AlbumDownLoad.dll
----------------------------------------
Zony.Lib.AlbumImgExport
    程序集版本:1.1.0.0
    Win32 版本:1.1.0.0
    基本代码:file:///C:/Users/damie/AppData/Local/Temp/Rar$EXa14036.18281/Plugins/Zony.Lib.AlbumImgExport.dll
----------------------------------------
Zony.Lib.MusicInfoEdit
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///C:/Users/damie/AppData/Local/Temp/Rar$EXa14036.18281/Plugins/Zony.Lib.MusicInfoEdit.dll
----------------------------------------
Zony.Lib.NCMConverter
    程序集版本:0.0.0.1
    Win32 版本:0.0.0.1
    基本代码:file:///C:/Users/damie/AppData/Local/Temp/Rar$EXa14036.18281/Plugins/Zony.Lib.NCMConverter.dll
----------------------------------------
Zony.Lib.NetEase
    程序集版本:2.2.1.0
    Win32 版本:2.2.1.0
    基本代码:file:///C:/Users/damie/AppData/Local/Temp/Rar$EXa14036.18281/Plugins/Zony.Lib.NetEase.dll
----------------------------------------
Zony.Lib.SongListDownload
    程序集版本:1.1.0.0
    Win32 版本:1.1.0.0
    基本代码:file:///C:/Users/damie/AppData/Local/Temp/Rar$EXa14036.18281/Plugins/Zony.Lib.SongListDownload.dll
----------------------------------------
Zony.Lib.TagLib
    程序集版本:1.2.3.0
    Win32 版本:1.2.3.0
    基本代码:file:///C:/Users/damie/AppData/Local/Temp/Rar$EXa14036.18281/Plugins/Zony.Lib.TagLib.dll
----------------------------------------
Zony.Lib.Net
    程序集版本:1.2.2.0
    Win32 版本:1.2.2.0
    基本代码:file:///C:/Users/damie/AppData/Local/Temp/Rar$EXa14036.18281/Zony.Lib.Net.DLL
----------------------------------------
System.Net.Http
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Newtonsoft.Json
    程序集版本:12.0.0.0
    Win32 版本:12.0.1.22727
    基本代码:file:///C:/Users/damie/AppData/Local/Temp/Rar$EXa14036.18281/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    程序集版本:4.0.0.0
    Win32 版本:4.7.3260.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    程序集版本:4.0.0.0
    Win32 版本:4.7.3260.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Web
    程序集版本:4.0.0.0
    Win32 版本:4.7.3282.0 built by: NET472REL1LAST_B
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。

**Comment by GameBelial** [comment]
好的，我查看一下问题。

**Comment by GameBelial** [comment]
@ligan92 请尝试一下 **[这个](https://github.com/GameBelial/ZonyLrcToolsX/releases/tag/0.1.9.3-201901171235)** 预览版本，看是否解决了你的问题。

**Comment by ligan92** [comment]
> @ligan92 请尝试一下 **[这个](https://github.com/GameBelial/ZonyLrcToolsX/releases/tag/0.1.9.3-201901171235)** 预览版本，看是否解决了你的问题。

您好，我刚刚测试了之前的歌曲，问题已解决，谢谢 : )

**Comment by GameBelial** [comment]
https://github.com/GameBelial/ZonyLrcToolsX/commit/0726ebbb8a0fc19de7142c22e38bf7d69325bad8
