### ISSUE TITLE
所有歌曲文件都无法找到歌词

### ISSUE THREAD

**Issue by Yulining0** [GameBelial/ZonyLrcToolsX#19]
![default](https://user-images.githubusercontent.com/39211548/51424347-4b964980-1c07-11e9-9582-13250198ab7d.PNG)
就像这样，是怎么回事呢？

**Comment by GameBelial** [comment]
![image](https://user-images.githubusercontent.com/3907132/51425673-4abae300-1c1a-11e9-8b56-d5dcd9f7cc88.png)
我这边测试是正常的哦，你新建一个文件夹，只存放几首歌曲文件再试呢，或者访问一下：[http://music.163.com/api/search/get/web](http://music.163.com/api/search/get/web) 地址，看是否是提示 503 错误。

**Comment by real-zony** [comment]
长时间没有回复，关闭此问题，如果仍然有疑问可以随时开启。
