### ISSUE TITLE
下载网易云歌单歌词是出错。就是歌单id超出int型定义长度，报错。

### ISSUE THREAD

**Issue by dshame** [GameBelial/ZonyLrcToolsX#20]
![image](https://user-images.githubusercontent.com/26822775/51483629-813c5d80-1dd4-11e9-894e-c60b7ab890e3.png)

下载源代码编译，稍微做了一些修改，，具体的我也没细看。。。简单的将int 变成string 成功下载网易云歌单歌词。作者可以借鉴一下。。。 cs文件  startup.cs 希望有用。

      private async void _button_Click(object sender, System.EventArgs e)
        {
            GlobalContext.Instance.UIContext.DisableTopButtons();
            ClearAllContainer();

            string  id = GetMusicDetailId();
            if (id.Length == 0)
            {
                GlobalContext.Instance.UIContext.EnableTopButtons();
                return;
            }

            try
            {
                NetEaseResultModel jsonModel = RequestNetEase(id);
                List<MusicInfoModel> infos = ConvertJsonModelToMusicInfoModel(jsonModel);
                await FillListView(infos);

                GlobalContext.Instance.MusicInfos.AddRange(infos);
                GlobalContext.Instance.UIContext.EnableTopButtons();
            }
            catch (ProxyException)
            {
                MessageBox.Show("代理服务器无法正常访问。", "错误", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        /// <summary>
        /// 将 Json 模型转换为 MusicInfoModel
        /// </summary>
        /// <param name="jsonObject">请求返回的 JSON 对象</param>
        /// <returns>转换成功的 MusicInfo 列表，如果失败返回 NULL</returns>
        private List<MusicInfoModel> ConvertJsonModelToMusicInfoModel(NetEaseResultModel jsonObject)
        {
            if (jsonObject.code != "200") return null;
            if (jsonObject.result == null) return null;
            if (jsonObject.result.tracks == null) return null;

            List<MusicInfoModel> result = new List<MusicInfoModel>();
            foreach (var info in jsonObject.result.tracks)
            {
                result.Add(new MusicInfoModel
                {
                    Song = info.name,
                    Artist = info.artists[0].name,
                    Album = info.album.name
                });
            }

            return result;
        }

        /// <summary>
        /// 对网易云 API 发起请求，获取歌单信息
        /// </summary>
        /// <param name="id">歌单 ID</param>
        private NetEaseResultModel RequestNetEase(string id)
        {
            var jsonResult = _httpClient.Get("http://music.163.com/api/playlist/detail", new
            {
                id,
                offset = 0,
                total = true,
                limit = 1000,
                n = 1000,
                csrf_token = string.Empty
            }, "http://music.163.com");

            return JsonConvert.DeserializeObject<NetEaseResultModel>(jsonResult);
        }

        /// <summary>
        /// 获取歌单 ID
        /// </summary>
        private string GetMusicDetailId()
        {
            var inputBox = new InputBox("请输入歌单 URL 或者歌单 ID", "网页版歌URL，例如:\r\n" +
                                         "http://music.163.com/#/playlist?id=716152005\r\n或者输入Id:716152005");
            inputBox.ShowDialog();

            if (string.IsNullOrWhiteSpace(inputBox.ResultText)) return null;

            if (int.TryParse(inputBox.ResultText, out int inputId)) return null;

            var regex = new Regex(@"(?<=id=)\d+");
            var match = regex.Match(inputBox.ResultText);
            if (!match.Success) return null;
            return match.Value;
        }

**Comment by GameBelial** [comment]
3q，已经做了更改，当然后面有其他功能性上的修改可以提交 PR，更加方便哦~😂
