### ISSUE TITLE
增加拖拽音乐入库功能

### ISSUE THREAD

**Issue by ligan92** [GameBelial/ZonyLrcToolsX#21]
建议作者大大增加直接拖拽音乐入库的功能。
有时音乐mp3所在目录较深，点击“扫描歌曲”设置路径需逐层点击才能找到目标路径，操作起来不太方便。作者能否考虑增加直接批量拖动音乐文件进软件的功能呢？Win10运行软件，拖动音乐进来，显示快捷方式的箭头图标，但文件没有拖入成功。使用管理员模式运行，拖动时是禁止图标，亦无法完成拖动入库的操作。
谢谢 ^.^

**Comment by GameBelial** [comment]
@ligan92 文件夹拖拽原生是支持的，该功能我之前有测试过，我这边再看一下是什么情况。

**Comment by ligan92** [comment]
> @ligan92 文件夹拖拽原生是支持的，该功能我之前有测试过，我这边再看一下是什么情况。

好的，谢谢您。我刚刚测试了文件夹拖动，是可行的，文件夹内的歌曲可以正常识别。如果支持文件拖动就更好啦。

**Comment by GameBelial** [comment]
文件拖动这块我看一下;

**Comment by real-zony** [comment]
@ligan92 已经更新，参考 [https://github.com/GameBelial/ZonyLrcToolsX/releases/tag/0.1.9.3-201904181157](https://github.com/GameBelial/ZonyLrcToolsX/releases/tag/0.1.9.3-201904181157) 。

**Comment by ligan92** [comment]
谢谢您。您提供的链接内有更新后的源代码，请问可否提供编译后的可执行文件呢？或者只需在之前版本可执行文件上添加一些源代码文件？技术小白，请多指教。谢谢

**Comment by real-zony** [comment]
@ligan92 已经补全二进制文件，名称叫 ZonyLrcToolsX.0.1.9.3-201904181157.zip，还是那个 Release 连接。

**Comment by ligan92** [comment]
谢谢您的回复和更新，已下载新版程序，测试拖拽音乐入库功能成功 : D
