### ISSUE TITLE
对ncm格式歌曲进行转换格式时，出现批量大部分特定歌曲转换失败的情况。

### ISSUE THREAD

**Issue by ysssgdhr** [GameBelial/ZonyLrcToolsX#24]
对ncm格式歌曲进行转换格式时，出现批量大部分特定歌曲转换失败的情况。

**Comment by ysssgdhr** [comment]
<img width="860" alt="屏幕快照" src="https://user-images.githubusercontent.com/24486813/57193359-be37f480-6f6c-11e9-9cb2-c43c9e69dd6d.png">

**Comment by real-zony** [comment]
@ysssgdhr 这部分失败的歌曲能否发一个出来呢？

**Comment by real-zony** [comment]
因长时间没有反馈问题信息，现将问题关闭，如果后续有其他疑问，可以再次开启本 Issue。
