### ISSUE TITLE
长久以来的感谢

### ISSUE THREAD

**Issue by linchenyejk** [GameBelial/ZonyLrcToolsX#3]
用这个工具很久了，让我获取歌词方便了不少，非常感谢。
由于一直用的是旧版，现在下载歌词（特别是网易里带翻译的歌词，下载下来的歌词排版会有问题）
虽然能用，但非常不方便进行修改操作
![1](https://user-images.githubusercontent.com/16831473/44307478-c0a1f080-a3d5-11e8-97a7-e675ef3a7326.jpg)
也许新版已经修复了这个功能吧？但我已经在这主页找不到更新的链接了。
能否提供解决此问题的方法或者添加新版的更新方式呢？

**Comment by GameBelial** [comment]
在此处拥有最新的下载链接：
https://github.com/GameBelial/ZonyLrcToolsX/releases
或者你可以加入 QQ 群(337656932)进行交流。
