### ISSUE TITLE
增加歌词共享(贡献)功能

### ISSUE THREAD

**Issue by real-zony** [GameBelial/ZonyLrcToolsX#32]
这个功能我一直想做，但由于工作等原因，一直没有在工具里面进行实现。

想要做这个功能的初衷，是因为网易云音乐等歌词源不知道什么时候会封掉这些 API。另一方面的原因，则是某些冷门歌曲是没有歌词的，这个时候用户就可以贡献自己的歌词数据。

所以想要建议一个歌词分享平台。有了分享平台之后，即便没有了其他的歌词源，也能够依靠分享平台为大家提供歌词下载服务。

**Comment by tomszheng** [comment]
Hello @GameBelial , 我个人觉得这个工作量或许太大了，毕竟世界上的歌曲那么多，建立单个平台并不太可能。

我个人的建议是，提供一个 lyric source 的接口给大家。 例如 apt-get 的 source 一样。 大家只要遵守接口的调用规则及歌词的文件格式等就可以了。 你这里的接口功能完善之后，只需要不断地添加别人的 source 就可以了。 

现在的情况或许是：你使用别人的歌词源API，或许需要每一个单独去实现，从而从不同的歌词源下载歌词。 **但是，你也可以定义一个这个项目所独有的API， 结合你对现有API的理解，制定一个歌词接入规则，让别的想要提供歌词的小伙伴follow你的idea。**

也就是说，我个人建议：提供一个歌词源的接口，而没有必要你自己去创建曲库什么的。

**Comment by real-zony** [comment]
@tomszheng 目前的想法也是这样，会有公开的 API 接口。另外在下载时，程序也会主动上传对应的 Lyric 文件丰富资源库。

**Comment by iusearch** [comment]
歌词匹配的话我建议跟musicbrainz和acounstID的接口对一下，现在有这个想法的具体仓库么

**Comment by real-zony** [comment]
@aliyuchang33 会放在下一个版本(Electron)做。

**Comment by real-zony** [comment]
- [ ] 提供歌词上传接口。
- [ ] 建立开放 API 平台，包括鉴权，限流等处理。

**Comment by real-zony** [comment]
本 Issue 暂时关闭，会在单独的 Issue 进行任务分解与跟踪。
