### ISSUE TITLE
Win10无法打开该应用程序

### ISSUE THREAD

**Issue by Mioioioio** [GameBelial/ZonyLrcToolsX#36]
进程页面会出现已停止然后进程结束，不知为何，net framework已经装至最新版本

**Comment by real-zony** [comment]
@Mioioioio 有详细的报错截图么？请确认是否是完全解压程序运行的。

**Comment by Mioioioio** [comment]
的确完全解压程序运行，双击应用程序不出现弹窗，查看任务管理器，该进程也仅会短暂出现，然后显示已停止，进程结束

**Comment by real-zony** [comment]
@Mioioioio 你使用的是最新的 Release 版本么？这块因为我在 Windows 10 几个版本都测试过，是可以正常打开的。或者放在其他盘完全解压运行试一下，另外 Plugins 要与 EXE 文件在一起哦。

**Comment by ricepeak** [comment]
亲测可用
https://gitee.com/jokers/ZonyLrcTools
下载其中的发行版
![image](https://user-images.githubusercontent.com/50504651/65509220-8b36d300-df04-11e9-8477-060a7811b559.png)
解压后以管理员身份运行，注意别更新版本；
如果第二次打不开，结束任务管理器相关进程，并删除解压文件夹的`Logfiles`文件夹。
