### ISSUE TITLE
双语歌词建议

### ISSUE THREAD

**Issue by lastwatch** [GameBelial/ZonyLrcToolsX#38]
建议能像ZonyLrcTools 0.0.3.0版一样，添加自行选择是否下载翻译歌词的选项，
望考虑，非常感谢。

**Comment by real-zony** [comment]
@lastwatch 正在开发的 1.0 版本当中是可以进行选择的，请等待更新。

**Comment by tomszheng** [comment]
@lastwatch , 今天我刚好需要下载歌词，试了一下 `0.1.9.3-201904181157`， 里面现在是可以选择不下载翻译的歌词的。只需要把插件下载里面的IsOpenTransLyric给修改一下就可以了。

```
{"Zony.Lib.NetEase":{"ReplaceLF":false,"Inline":true,"IsOpenTransLyric":false}}
```

只是目前重新生成的lrc里面还会有上一次的内容，再优化一下就更完美了。

**Comment by lastwatch** [comment]
非常感谢，没问题了
