### ISSUE TITLE
无法下载专辑歌词

### ISSUE THREAD

**Issue by zlf179** [GameBelial/ZonyLrcToolsX#39]
如图所示
![屏幕截图(23)](https://user-images.githubusercontent.com/26280126/61654822-8adc4a80-acbd-11e9-98a8-ee465c49c136.png)

下面是详细信息

有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.ArgumentException: Could not cast or convert from System.String to Zony.Lib.Net.JsonModels.NetEase.NetEaseInnerResultModel.
   在 Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   在 Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)

************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.8.3815.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
ZonyLrcTools
    程序集版本:0.1.9.3
    Win32 版本:0.1.9.3
    基本代码:file:///C:/Users/77032/Desktop/%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9%20(2)/ZonyLrcTools.exe
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.8.3815.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.8.3801.0 built by: NET48REL1LAST_B
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Zony.Lib.Infrastructures
    程序集版本:1.1.0.0
    Win32 版本:1.1.0.0
    基本代码:file:///C:/Users/77032/Desktop/%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9%20(2)/Zony.Lib.Infrastructures.DLL
----------------------------------------
Castle.Windsor
    程序集版本:4.0.0.0
    Win32 版本:4.1.1
    基本代码:file:///C:/Users/77032/Desktop/%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9%20(2)/Castle.Windsor.DLL
----------------------------------------
Castle.Core
    程序集版本:4.0.0.0
    Win32 版本:4.3.1
    基本代码:file:///C:/Users/77032/Desktop/%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9%20(2)/Castle.Core.DLL
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.8.3815.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    程序集版本:0.0.0.0
    Win32 版本:4.8.3815.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Zony.Lib.Plugin
    程序集版本:1.3.1.0
    Win32 版本:1.3.1.0
    基本代码:file:///C:/Users/77032/Desktop/%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9%20(2)/Zony.Lib.Plugin.DLL
----------------------------------------
Zony.Lib.UIComponents
    程序集版本:1.0.1.0
    Win32 版本:1.0.1.0
    基本代码:file:///C:/Users/77032/Desktop/%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9%20(2)/Zony.Lib.UIComponents.DLL
----------------------------------------
log4net
    程序集版本:2.0.8.0
    Win32 版本:2.0.8.0
    基本代码:file:///C:/Users/77032/Desktop/%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9%20(2)/log4net.DLL
----------------------------------------
taglib-sharp
    程序集版本:2.1.0.0
    Win32 版本:2.1.0.0
    基本代码:file:///C:/Users/77032/Desktop/%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9%20(2)/Plugins/taglib-sharp.dll
----------------------------------------
Zony.Lib.AlbumDownLoad
    程序集版本:1.1.1.1
    Win32 版本:1.1.1.1
    基本代码:file:///C:/Users/77032/Desktop/%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9%20(2)/Plugins/Zony.Lib.AlbumDownLoad.dll
----------------------------------------
Zony.Lib.AlbumImgExport
    程序集版本:1.1.0.0
    Win32 版本:1.1.0.0
    基本代码:file:///C:/Users/77032/Desktop/%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9%20(2)/Plugins/Zony.Lib.AlbumImgExport.dll
----------------------------------------
Zony.Lib.MusicInfoEdit
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///C:/Users/77032/Desktop/%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9%20(2)/Plugins/Zony.Lib.MusicInfoEdit.dll
----------------------------------------
Zony.Lib.NCMConverter
    程序集版本:0.0.0.1
    Win32 版本:0.0.0.1
    基本代码:file:///C:/Users/77032/Desktop/%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9%20(2)/Plugins/Zony.Lib.NCMConverter.dll
----------------------------------------
Zony.Lib.NetEase
    程序集版本:2.2.1.0
    Win32 版本:2.2.1.0
    基本代码:file:///C:/Users/77032/Desktop/%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9%20(2)/Plugins/Zony.Lib.NetEase.dll
----------------------------------------
Zony.Lib.SongListDownload
    程序集版本:1.1.0.0
    Win32 版本:1.1.0.0
    基本代码:file:///C:/Users/77032/Desktop/%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9%20(2)/Plugins/Zony.Lib.SongListDownload.dll
----------------------------------------
Zony.Lib.TagLib
    程序集版本:1.2.3.0
    Win32 版本:1.2.3.0
    基本代码:file:///C:/Users/77032/Desktop/%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9%20(2)/Plugins/Zony.Lib.TagLib.dll
----------------------------------------
Zony.Lib.Net
    程序集版本:1.2.2.0
    Win32 版本:1.2.2.0
    基本代码:file:///C:/Users/77032/Desktop/%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9%20(2)/Zony.Lib.Net.DLL
----------------------------------------
System.Net.Http
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Newtonsoft.Json
    程序集版本:12.0.0.0
    Win32 版本:12.0.1.22727
    基本代码:file:///C:/Users/77032/Desktop/%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9%20(2)/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    程序集版本:4.0.0.0
    Win32 版本:4.8.3825.0 built by: NET48REL1LAST_B
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Web
    程序集版本:4.0.0.0
    Win32 版本:4.8.3815.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。

不知道怎么解决。。。

**Comment by real-zony** [comment]
该问题可能是由于网络引起的...请检查是否启用网络代理软件，或者运行软件的电脑 IP 已经被网易云音乐限制访问。

**Comment by zlf179** [comment]
> 该问题可能是由于网络引起的...请检查是否启用网络代理软件，或者运行软件的电脑 IP 已经被网易云音乐限制访问。

我在国外 这里的确是被网易云地区问题版权限制了 但是我用了一个国内代理 他还是报错诶  同一个代理地址 我在网易云内使用 所有歌都能听

**Comment by real-zony** [comment]
那你可以在软件的网络代理设置里面配置本地代理。
以 SSR 为例，我可以在全局设置里面启用本地代理：
![image](https://user-images.githubusercontent.com/3907132/61707173-6b582700-ad7c-11e9-8ac8-d17922e2ee01.png)
![image](https://user-images.githubusercontent.com/3907132/61707188-74e18f00-ad7c-11e9-8115-4e4aafb51690.png)
那么你可以在软件里面设置代理服务器 IP：127.0.0.1 ，端口 1080 之后再进行测试。
