### ISSUE TITLE
周杰伦的歌 lrc与歌曲不同

### ISSUE THREAD

**Issue by ghost** [GameBelial/ZonyLrcToolsX#41]
150多首周董的歌，大多都是歌词与歌曲不同。是不是网易云自己的问题？

![捕获](https://user-images.githubusercontent.com/20292195/62996930-1d28d600-be99-11e9-8b82-19fce3d8946f.PNG)

**Comment by ghost** [comment]
日志中无输出

**Comment by ghost** [comment]
编译运行1.0版本，结果发现不能下载任何一首歌曲

**Comment by real-zony** [comment]
@pechpo 1.0 版本目前还没有完成开发，请使用 Release 的 0.19 版本。如果是歌曲无法正常下载 Lyric 歌词，请上传一两首歌曲我这边做一下测试。

**Comment by ghost** [comment]
[歌曲样本.zip](https://github.com/GameBelial/ZonyLrcToolsX/files/3503973/default.zip)

**Comment by ghost** [comment]
我怀疑是网易云没有配套歌词 @GameBelial

**Comment by real-zony** [comment]
@pechpo emmm，有可能，周董的歌不是都下架了么，这边我再看看。

**Comment by real-zony** [comment]
[ZonyLrcToolsX_Build_201910032146.zip](https://github.com/GameBelial/ZonyLrcToolsX/files/3686359/ZonyLrcToolsX_Build_201910032146.zip)

@pechpo 针对于提出的问题，确实是由于网易云音乐下架了周董的歌，你可以使用上面的 1.0 预览版，并选择 QQ 音乐源进行下载操作。
![image](https://user-images.githubusercontent.com/3907132/66132305-6a1e6280-e627-11e9-8aae-092893ebab40.png)
![image](https://user-images.githubusercontent.com/3907132/66132324-71de0700-e627-11e9-8f9e-15ed6f388a66.png)
