### ISSUE TITLE
An Unknow Error of 0.1.9.3-201904181157 Vr.

### ISSUE THREAD

**Issue by ChiseHatori** [GameBelial/ZonyLrcToolsX#42]
************** 异常文本 **************
System.AggregateException: 发生一个或者多个异常，调用失败，SingleMusicInfoLoadEventData ---> System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.ArgumentOutOfRangeException: InvalidArgument=“0”的值对于“index”无效。
参数名: index
   在 System.Windows.Forms.ListView.SelectedListViewItemCollection.get_Item(Int32 index)
   在 ZonyLrcTools.Events.SingleMusicInfoLoadEvent.HandleEvent(SingleMusicInfoLoadEventData eventData)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   在 System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Zony.Lib.Infrastructures.EventBus.EventBus.TriggerHandlingException(Type eventType, Object eventSource, IEventData eventData, List`1 exceptions)
   --- 内部异常堆栈跟踪的结尾 ---
   在 Zony.Lib.Infrastructures.EventBus.EventBus.Trigger(Type eventType, Object eventSource, IEventData eventData)
   在 Zony.Lib.Infrastructures.EventBus.EventBus.Trigger[TEventData](Object eventSource, TEventData eventData)
   在 Zony.Lib.Infrastructures.EventBus.EventBus.Trigger[TEventData](TEventData eventData)
   在 ZonyLrcTools.Forms.Form_Startup.<>c__DisplayClass15_0`1.<GenerateClickDelegate>b__0(Object <p0>, EventArgs <p1>)
   在 System.Windows.Forms.Control.OnClick(EventArgs e)
   在 System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   在 System.Windows.Forms.ListView.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---> (内部异常 #0) System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.ArgumentOutOfRangeException: InvalidArgument=“0”的值对于“index”无效。
参数名: index
   在 System.Windows.Forms.ListView.SelectedListViewItemCollection.get_Item(Int32 index)
   在 ZonyLrcTools.Events.SingleMusicInfoLoadEvent.HandleEvent(SingleMusicInfoLoadEventData eventData)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   在 System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Zony.Lib.Infrastructures.EventBus.EventBus.TriggerHandlingException(Type eventType, Object eventSource, IEventData eventData, List`1 exceptions)<---

************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.8.3815.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
ZonyLrcTools
    程序集版本:0.1.9.3
    Win32 版本:0.1.9.3
    基本代码:file:///C:/Users/AlexHunter/Desktop/ZonyLrcToolsX/ZonyLrcToolsX.0.1.9.3-201904181157/ZonyLrcTools.exe
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.8.3815.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.8.3801.0 built by: NET48REL1LAST_B
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Zony.Lib.Infrastructures
    程序集版本:1.1.0.0
    Win32 版本:1.1.0.0
    基本代码:file:///C:/Users/AlexHunter/Desktop/ZonyLrcToolsX/ZonyLrcToolsX.0.1.9.3-201904181157/Zony.Lib.Infrastructures.DLL
----------------------------------------
Castle.Windsor
    程序集版本:4.0.0.0
    Win32 版本:4.1.1
    基本代码:file:///C:/Users/AlexHunter/Desktop/ZonyLrcToolsX/ZonyLrcToolsX.0.1.9.3-201904181157/Castle.Windsor.DLL
----------------------------------------
Castle.Core
    程序集版本:4.0.0.0
    Win32 版本:4.3.1
    基本代码:file:///C:/Users/AlexHunter/Desktop/ZonyLrcToolsX/ZonyLrcToolsX.0.1.9.3-201904181157/Castle.Core.DLL
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.8.3815.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    程序集版本:0.0.0.0
    Win32 版本:4.8.3815.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Zony.Lib.Plugin
    程序集版本:1.3.1.0
    Win32 版本:1.3.1.0
    基本代码:file:///C:/Users/AlexHunter/Desktop/ZonyLrcToolsX/ZonyLrcToolsX.0.1.9.3-201904181157/Zony.Lib.Plugin.DLL
----------------------------------------
Zony.Lib.UIComponents
    程序集版本:1.0.1.0
    Win32 版本:1.0.1.0
    基本代码:file:///C:/Users/AlexHunter/Desktop/ZonyLrcToolsX/ZonyLrcToolsX.0.1.9.3-201904181157/Zony.Lib.UIComponents.DLL
----------------------------------------
log4net
    程序集版本:2.0.8.0
    Win32 版本:2.0.8.0
    基本代码:file:///C:/Users/AlexHunter/Desktop/ZonyLrcToolsX/ZonyLrcToolsX.0.1.9.3-201904181157/log4net.DLL
----------------------------------------
taglib-sharp
    程序集版本:2.1.0.0
    Win32 版本:2.1.0.0
    基本代码:file:///C:/Users/AlexHunter/Desktop/ZonyLrcToolsX/ZonyLrcToolsX.0.1.9.3-201904181157/Plugins/taglib-sharp.dll
----------------------------------------
Zony.Lib.AlbumDownLoad
    程序集版本:1.1.1.1
    Win32 版本:1.1.1.1
    基本代码:file:///C:/Users/AlexHunter/Desktop/ZonyLrcToolsX/ZonyLrcToolsX.0.1.9.3-201904181157/Plugins/Zony.Lib.AlbumDownLoad.dll
----------------------------------------
Zony.Lib.AlbumImgExport
    程序集版本:1.1.0.0
    Win32 版本:1.1.0.0
    基本代码:file:///C:/Users/AlexHunter/Desktop/ZonyLrcToolsX/ZonyLrcToolsX.0.1.9.3-201904181157/Plugins/Zony.Lib.AlbumImgExport.dll
----------------------------------------
Zony.Lib.MusicInfoEdit
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///C:/Users/AlexHunter/Desktop/ZonyLrcToolsX/ZonyLrcToolsX.0.1.9.3-201904181157/Plugins/Zony.Lib.MusicInfoEdit.dll
----------------------------------------
Zony.Lib.NCMConverter
    程序集版本:0.0.0.1
    Win32 版本:0.0.0.1
    基本代码:file:///C:/Users/AlexHunter/Desktop/ZonyLrcToolsX/ZonyLrcToolsX.0.1.9.3-201904181157/Plugins/Zony.Lib.NCMConverter.dll
----------------------------------------
Zony.Lib.NetEase
    程序集版本:2.2.1.0
    Win32 版本:2.2.1.0
    基本代码:file:///C:/Users/AlexHunter/Desktop/ZonyLrcToolsX/ZonyLrcToolsX.0.1.9.3-201904181157/Plugins/Zony.Lib.NetEase.dll
----------------------------------------
Zony.Lib.SongListDownload
    程序集版本:1.1.0.0
    Win32 版本:1.1.0.0
    基本代码:file:///C:/Users/AlexHunter/Desktop/ZonyLrcToolsX/ZonyLrcToolsX.0.1.9.3-201904181157/Plugins/Zony.Lib.SongListDownload.dll
----------------------------------------
Zony.Lib.TagLib
    程序集版本:1.2.3.0
    Win32 版本:1.2.3.0
    基本代码:file:///C:/Users/AlexHunter/Desktop/ZonyLrcToolsX/ZonyLrcToolsX.0.1.9.3-201904181157/Plugins/Zony.Lib.TagLib.dll
----------------------------------------
Zony.Lib.Net
    程序集版本:1.2.2.0
    Win32 版本:1.2.2.0
    基本代码:file:///C:/Users/AlexHunter/Desktop/ZonyLrcToolsX/ZonyLrcToolsX.0.1.9.3-201904181157/Zony.Lib.Net.DLL
----------------------------------------
System.Net.Http
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Newtonsoft.Json
    程序集版本:12.0.0.0
    Win32 版本:12.0.1.22727
    基本代码:file:///C:/Users/AlexHunter/Desktop/ZonyLrcToolsX/ZonyLrcToolsX.0.1.9.3-201904181157/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    程序集版本:4.0.0.0
    Win32 版本:4.8.3825.0 built by: NET48REL1LAST_B
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Web
    程序集版本:4.0.0.0
    Win32 版本:4.8.3815.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

**Comment by ChiseHatori** [comment]
Just pop up constantly..
And some songs do have caption on NeteaseMusic just couldn't found by the app😶😶
and Wish U GL..70th anniversary 2morrow😉

**Comment by real-zony** [comment]
[ZonyLrcToolsX_Build_201910032106.zip](https://github.com/GameBelial/ZonyLrcToolsX/files/3686164/ZonyLrcToolsX_Build_201910032106.zip)

Hello,you can try this pre-release version.

**Comment by real-zony** [comment]
长时间没有反馈，暂时关闭问题，如果还未解决，请重新打开。
