### ISSUE TITLE
无法准确识别下载歌词

### ISSUE THREAD

**Issue by ligan92** [GameBelial/ZonyLrcToolsX#46]
您好，我使用ZonyLrcToolsX和ZonyLrcTools无法下载 黄妃 - 追追追 一曲的歌词
前者显示没有找到歌词，后者下载的歌词与该歌曲无关
歌曲文件请见如下链接：
链接: https://pan.baidu.com/s/1gbLSYTd4dGaxn5iNJuB9mQ
提取码: n8dm
谢谢您的帮助
祝好

**Comment by real-zony** [comment]
好的，我会看一下。

**Comment by real-zony** [comment]
@ligan92 软件使用的 Tagsharp 似乎无法识别目标歌曲的 Tag 信息，请使用 Mp3Tag 打开歌曲保存标签信息。之后在使用软件进行下载即可正常。

**Comment by RouJiANG-14** [comment]
居然还有更新！简直业界良心！！！

**Comment by real-zony** [comment]
长时间没有回复，暂时关闭 Issue，有需要可以重新开启。
