### ISSUE TITLE
使用软件的环境配置问题

### ISSUE THREAD

**Issue by wenjor** [GameBelial/ZonyLrcToolsX#47]
一路从ZonyLrcDownLoad使用过来，但是在ZonyLrcToolsX0.18之后的版本都无法正常运行，试着在win10功能中启用了.net 4.8，甚至关掉了.net 3.0，但0.19就是不运行。。。。。。一阵折腾后0.18也不运行了。（都是执行文件双击后有加载的转圈动画，然后。。。。没有任何进程启动）
运行环境是缺了些什么吗，平时用Walkman听歌的歌词一直靠您的软件，现在我实在是解决不了问题了

**Comment by real-zony** [comment]
是否已经解压之后进行运行的？如果还是不行，可以加我 QQ 243387971，我远程查看一下。
