### ISSUE TITLE
歌曲扫描加载的最后阶段出现问题

### ISSUE THREAD

**Issue by wenjor** [GameBelial/ZonyLrcToolsX#49]
文件数目确认无误，但是具体扫描加载的进度条在满格阶段报错（歌曲数目为411，应该没有爆栈）

2019年10月15日 14:54:15 - 产生了异常。
异常提示信息：参数无效。
异常堆栈信息：   在 System.Drawing.Image.FromStream(Stream stream, Boolean useEmbeddedColorManagement, Boolean validateImageData)
   在 System.Drawing.Image.FromStream(Stream stream)
   在 ZonyLrcToolsX.Forms.MainForm.listView_MusicList_SelectedIndexChanged(Object sender, EventArgs e)
   在 System.Windows.Forms.ListView.OnSelectedIndexChanged(EventArgs e)
   在 System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   在 System.Windows.Forms.ListView.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by real-zony** [comment]
@wenjor 当时你提示异常的时候，第一首歌曲信息是什么呢？

**Comment by real-zony** [comment]
已解决。(https://github.com/GameBelial/ZonyLrcToolsX/commit/ed1e28a17df026f74f9f1e9905415d79b193153c)
