### ISSUE TITLE
如何更换歌词源至qq音乐

### ISSUE THREAD

**Issue by Naexen** [GameBelial/ZonyLrcToolsX#5]
以及添加图片源选择，图片选择，歌词来源/歌词标签等

**Comment by Naexen** [comment]
有部分歌曲网易云不支持的直接就下载了完全不相关的图片和歌词，一个个校对比较繁琐

**Comment by GameBelial** [comment]
QQ 音乐源目前没有做相应的适配，该功能可以放到 0.1.9 再做更新.

**Comment by real-zony** [comment]
See https://github.com/GameBelial/ZonyLrcToolsX/commit/c5c65aabcf3c8c6b97dde2b1305e8039845fe9e8
