### ISSUE TITLE
看不懂

### ISSUE THREAD

**Issue by Simonlonz** [GameBelial/ZonyLrcToolsX#51]
2019年11月18日 16:58:25 - 产生了异常。
异常提示信息：对路径“G:\Music\Blue - All Rise.mp3”的访问被拒绝。
异常堆栈信息：   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   在 TagLib.File.LocalFileAbstraction.get_WriteStream() 位置 C:\code\taglib-sharp\src\TaglibSharp\File.cs:行号 1600
   在 TagLib.File.set_Mode(AccessMode value) 位置 C:\code\taglib-sharp\src\TaglibSharp\File.cs:行号 411
   在 TagLib.NonContainer.File.Save() 位置 C:\code\taglib-sharp\src\TaglibSharp\NonContainer\File.cs:行号 206
   在 ZonyLrcToolsX.Infrastructure.MusicTag.TagLib.MusicInfoLoaderByTagLib.Load(String musicFilePath) 位置 D:\项目\开源项目\ZonyLrcToolsX\ZonyLrcToolsX\ZonyLrcToolsX\Infrastructure\MusicTag\TagLib\MusicInfoLoaderByTagLib.cs:行号 42
   在 ZonyLrcToolsX.Infrastructure.MusicTag.TagLib.MusicInfoLoaderByTagLib.LoadAsync(String musicFilePath) 位置 D:\项目\开源项目\ZonyLrcToolsX\ZonyLrcToolsX\ZonyLrcToolsX\Infrastructure\MusicTag\TagLib\MusicInfoLoaderByTagLib.cs:行号 51
   在 ZonyLrcToolsX.Forms.MainForm.<>c__DisplayClass8_0.<<ToolStripButton_SearchMusicFile_Click>b__0>d.MoveNext() 位置 D:\项目\开源项目\ZonyLrcToolsX\ZonyLrcToolsX\ZonyLrcToolsX\Forms\MainForm.cs:行号 88
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by real-zony** [comment]
@Simonlonz 尝试更换文件目录，或者以管理员方式运行程序。

**Comment by real-zony** [comment]
长时间没有回复，关闭 Issue，如果有需要可以重新开启。
