### ISSUE TITLE
1.0版本问题，扫描多文件（1000+）单文件夹无响应，某些歌添加封面图会自动退出，某些歌的歌词无法生成

### ISSUE THREAD

**Issue by inkossi** [GameBelial/ZonyLrcToolsX#52]
exception.log

2019年11月29日 11:33:05 - 产生了异常。
异常提示信息：没有搜索到指定的歌曲。
异常堆栈信息：   在 ZonyLrcToolsX.Downloader.Album.NetEase.NetEaseCloudMusicAlbumDownloader.<DownloadAsync>d__2.MoveNext() 位置 D:\项目\开源项目\ZonyLrcToolsX\ZonyLrcToolsX\ZonyLrcToolsX\Downloader\Album\NetEase\NetEaseCloudMusicAlbumDownloader.cs:行号 40
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException[TResult](Task`1 task)
   在 Nito.AsyncEx.AsyncContext.<>c__DisplayClass16_0`1.<Run>b__0(Task`1 t)
   在 System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException[TResult](Task`1 task)
   在 Nito.AsyncEx.AsyncContext.Run[TResult](Func`1 action)
   在 ZonyLrcToolsX.Downloader.Album.NetEase.NetEaseCloudMusicAlbumDownloader.Download(MusicInfo musicInfo) 位置 D:\项目\开源项目\ZonyLrcToolsX\ZonyLrcToolsX\ZonyLrcToolsX\Downloader\Album\NetEase\NetEaseCloudMusicAlbumDownloader.cs:行号 52
   在 ZonyLrcToolsX.Forms.MainForm.ToolStripButton_DownloadAlbumImage_Click(Object sender, EventArgs e) 位置 D:\项目\开源项目\ZonyLrcToolsX\ZonyLrcToolsX\ZonyLrcToolsX\Forms\MainForm.cs:行号 183
   在 System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   在 System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   在 System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   在 System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   在 System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   在 System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   在 System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   在 System.Windows.Forms.ToolStrip.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

无法生成歌词的歌曲简单列几首，Karen Souza - Every Breath You Take，Klaus & Kinski - Mengele y el amor，这些歌词在基于网易云音乐歌词网站：http://lrc.opqnext.com/ 都可以搜索出来，应该是在遇到多版本的时候，会选择排名比较靠前的歌词，但是排名靠前的并没有添加歌词。

**Comment by real-zony** [comment]
@inkossi 你列举的这几首歌曲排名前几首的都是没有歌词的，所以是无法生成歌词。至于报错的问题，请尝试最新的 Release 版本。
