### ISSUE TITLE
201910200219 版本还是会因为没有搜索到指定歌曲而异常退出

### ISSUE THREAD

**Issue by VincentGaoHJ** [GameBelial/ZonyLrcToolsX#53]
2019年12月03日 14:15:27 - 产生了异常。
异常提示信息：没有搜索到指定的歌曲。
异常堆栈信息：   在 ZonyLrcToolsX.Downloader.Album.NetEase.NetEaseCloudMusicAlbumDownloader.<DownloadAsync>d__2.MoveNext() 位置 D:\项目\开源项目\ZonyLrcToolsX\ZonyLrcToolsX\ZonyLrcToolsX\Downloader\Album\NetEase\NetEaseCloudMusicAlbumDownloader.cs:行号 40
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException[TResult](Task`1 task)
   在 Nito.AsyncEx.AsyncContext.<>c__DisplayClass16_0`1.<Run>b__0(Task`1 t)
   在 System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException[TResult](Task`1 task)
   在 Nito.AsyncEx.AsyncContext.Run[TResult](Func`1 action)
   在 ZonyLrcToolsX.Downloader.Album.NetEase.NetEaseCloudMusicAlbumDownloader.Download(MusicInfo musicInfo) 位置 D:\项目\开源项目\ZonyLrcToolsX\ZonyLrcToolsX\ZonyLrcToolsX\Downloader\Album\NetEase\NetEaseCloudMusicAlbumDownloader.cs:行号 52
   在 ZonyLrcToolsX.Forms.MainForm.ToolStripButton_DownloadAlbumImage_Click(Object sender, EventArgs e) 位置 D:\项目\开源项目\ZonyLrcToolsX\ZonyLrcToolsX\ZonyLrcToolsX\Forms\MainForm.cs:行号 183
   在 System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   在 System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   在 System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   在 System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   在 System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   在 System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   在 System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   在 System.Windows.Forms.ToolStrip.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by real-zony** [comment]
@VincentGaoHJ 请尝试 https://github.com/GameBelial/ZonyLrcToolsX/releases/tag/1.0.0.2 版本，是否还存在该问题。如果仍然存在，请重新打开 Issue。
