### ISSUE TITLE
来源是QQ音乐时下载的歌词会普遍缺少最后一句

### ISSUE THREAD

**Issue by ClydeWong** [GameBelial/ZonyLrcToolsX#55]
网易的来源貌似没有这个问题

**Comment by real-zony** [comment]
@ClydeWong 是最新的版本么？这个问题我记得是解决了的。

**Comment by ClydeWong** [comment]
> @ClydeWong 是最新的版本么？这个问题我记得是解决了的。

是1.0.0.1版本 QQ的来源会直接缺少最后一句的原文和译文 网易的来源有一定概率出现最后一句丢失译文

**Comment by real-zony** [comment]
@ClydeWong 有具体的歌曲名和歌手信息么？我这边好测试一下。

**Comment by ClydeWong** [comment]
![image](https://user-images.githubusercontent.com/7686134/70389163-9fb04500-19f6-11ea-9628-c615f3f09ff7.png)
例如这一首 梁静茹 - 会呼吸的痛

**Comment by ClydeWong** [comment]
此外还有两点改良建议想提
1.歌词里原来已有的空段能否在下载时保留下来 例如此处
![image](https://user-images.githubusercontent.com/7686134/70389250-d0dd4500-19f7-11ea-98b0-923f67abd711.png)

2.有翻译的歌词可不可以增加一个这种输出形式的选择 这种排版比原文译文合并同行输出更适合手机端的观看
![image](https://user-images.githubusercontent.com/7686134/70389280-2b76a100-19f8-11ea-9f32-a48fab14e3c2.png)

**Comment by real-zony** [comment]
@ClydeWong 该问题应该是解决了的，参考 https://github.com/GameBelial/ZonyLrcToolsX/commit/510571915439c51127dbde7e1264e1938c71d49d，我稍后发布一个最新的 Release 版本。
![image](https://user-images.githubusercontent.com/3907132/70443203-b5933800-1ad2-11ea-8265-ef950ca82aa0.png)

**Comment by real-zony** [comment]
@ClydeWong https://github.com/GameBelial/ZonyLrcToolsX/releases/tag/1.0.0.2
如果还是有问题，请重新打开本 Issue。
