### ISSUE TITLE
1.0.0.2 版本网易云音乐接口没有正常返回结果

### ISSUE THREAD

**Issue by VincentGaoHJ** [GameBelial/ZonyLrcToolsX#56]
问题出在 六三四-哀と愁（白 Remix）这首歌，是一首纯音乐，将这首歌从列表中剔除之后运行正常。

问题不大，可以随时关掉此 Issue。

报错信息：
歌曲名：六三四-哀と愁（白 Remix） - 歌手名：白
2019年12月09日 23:09:42 - 产生了异常。
异常提示信息：网易云音乐接口没有正常返回结果...
异常堆栈信息：   在 ZonyLrcToolsX.Downloader.Lyric.NetEase.NetEaseCloudMusicLyricDownloader.ValidateResponse(MusicSearchResponseModel searchResult, MusicInfo musicInfo)
   在 ZonyLrcToolsX.Downloader.Lyric.NetEase.NetEaseCloudMusicLyricDownloader.<DownloadAsync>d__1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 ZonyLrcToolsX.Forms.MainForm.<>c__DisplayClass9_1.<<ToolStripButton_DownloadLyric_Click>b__2>d.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 ZonyLrcToolsX.Infrastructure.TaskWorker.<RunAsync>d__4.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 ZonyLrcToolsX.Forms.MainForm.<ToolStripButton_DownloadLyric_Click>d__9.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by real-zony** [comment]
https://github.com/GameBelial/ZonyLrcToolsX/commit/66c0805831a104425e62bd7050586a60920c080d 已解决。
