### ISSUE TITLE
有些歌曲的名称会被识别为乱码 

### ISSUE THREAD

**Issue by gaoxingeasy** [GameBelial/ZonyLrcToolsX#57]
[有些歌曲的名称会被识别为乱码，但却能识别出相应的专辑图片

[GALA - 追梦赤子心.zip](https://github.com/GameBelial/ZonyLrcToolsX/files/3981507/GALA.-.zip)
![561576723973_ pic](https://user-images.githubusercontent.com/59036583/71140972-bef86f00-224d-11ea-9a9e-0081351ae96f.jpg)

> @gaoxingeasy有相关的文件能上传一下么？

**Comment by real-zony** [comment]
@gaoxingeasy 有相关的文件能上传一下么？

**Comment by real-zony** [comment]
@gaoxingeasy 已经确认是 taglib 的问题，临时处理方式是采用 4.0.0 preview，使用默认的 FileName TagLoad，将 Taglib 禁用读取标签信息。
