### ISSUE TITLE
扫描完歌曲就崩溃了

### ISSUE THREAD

**Issue by happyfence** [GameBelial/ZonyLrcToolsX#59]
[exception.log](https://github.com/GameBelial/ZonyLrcToolsX/files/4007895/exception.log)

**Comment by happyfence** [comment]
2019年12月29日 16:17:19 - 产生了异常。
异常提示信息：指定的参数已超出有效值的范围。
参数名: length
异常堆栈信息：   在 TagLib.ByteVector.Mid(Int32 startIndex, Int32 length) 位置 C:\code\taglib-sharp\src\TaglibSharp\ByteVector.cs:行号 439
   在 TagLib.Flac.Picture..ctor(ByteVector data) 位置 C:\code\taglib-sharp\src\TaglibSharp\Flac\Picture.cs:行号 94
   在 TagLib.Flac.Metadata..ctor(IEnumerable`1 blocks) 位置 C:\code\taglib-sharp\src\TaglibSharp\Flac\File.cs:行号 574
   在 TagLib.Flac.File.ReadStart(Int64 start, ReadStyle propertiesStyle) 位置 C:\code\taglib-sharp\src\TaglibSharp\Flac\File.cs:行号 358
   在 TagLib.NonContainer.File.Read(ReadStyle propertiesStyle) 位置 C:\code\taglib-sharp\src\TaglibSharp\NonContainer\File.cs:行号 374
   在 TagLib.Flac.File..ctor(IFileAbstraction abstraction, ReadStyle propertiesStyle) 位置 C:\code\taglib-sharp\src\TaglibSharp\Flac\File.cs:行号 138   在 TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle) 位置 C:\code\taglib-sharp\src\TaglibSharp\File.cs:行号 1302
   在 ZonyLrcToolsX.Infrastructure.MusicTag.TagLib.MusicInfoLoaderByTagLib.Load(String musicFilePath)
   在 ZonyLrcToolsX.Infrastructure.MusicTag.TagLib.MusicInfoLoaderByTagLib.LoadAsync(String musicFilePath)
   在 ZonyLrcToolsX.Forms.MainForm.<>c__DisplayClass8_0.<<ToolStripButton_SearchMusicFile_Click>b__0>d.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by real-zony** [comment]
@happyfence 该问题是由于 Taglib 标签加载器引起的，在 4.0.0 preview 中，你可以尝试禁用该标签加载器，使用 FileName TagLoader 加载歌曲标签信息。
