### ISSUE TITLE
后期生成命令行存在问题

### ISSUE THREAD

**Issue by lim0513** [GameBelial/ZonyLrcToolsX#6]
第一次下载时exe文件夹下没有plugins目录，会导致复制文件到plugins文件上，而不是建立文件夹。
原命令：
copy $(TargetPath) $(SolutionDir)\ZonyLrcTools\bin\Debug\Plugins
copy $(TargetPath) $(SolutionDir)\ZonyLrcTools\bin\Release\Plugins
建议修改为：
xcopy $(TargetPath) $(SolutionDir)\ZonyLrcTools\bin\\$(ConfigurationName)\Plugins\

另外建议nuget里把主工程也引用【taglib】包，可以避免手动复制相关DLL到输出目录。

**Comment by lim0513** [comment]
我个人非常喜欢这个工具，给音乐播放器灌歌后直接简单运行以下就能导入歌词了，真是非常方便。希望作者能够坚持维护下去，我也愿意对项目贡献一些力量，虽然很微薄。感谢作者！

**Comment by GameBelial** [comment]
感谢你的意见，已经 update ，也希望这个工具能够帮助到你。

**Comment by GameBelial** [comment]
当然如果你想贡献代码的话，可以 fork 本项目，提交你的更改到你的远程 Git 仓库，然后通过提交 PR 与我的主分支合并。
