### ISSUE TITLE
1.0.0.2下载歌词失败

### ISSUE THREAD

**Issue by jjss520** [GameBelial/ZonyLrcToolsX#64]
2020年04月11日 10:05:11 - 产生了异常。
异常提示信息：根据验证过程，远程证书无效。
异常堆栈信息：   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)

**Comment by real-zony** [comment]
@jjss520 无法复现，请尝试使用 4.0.0 preview 再试。
