### ISSUE TITLE
扫描完文件后报错

### ISSUE THREAD

**Issue by 91Metis** [GameBelial/ZonyLrcToolsX#65]
2020年05月26日 16:19:55 - 产生了异常。
异常提示信息：指定的参数已超出有效值的范围。
参数名: length
异常堆栈信息：   在 TagLib.ByteVector.Mid(Int32 startIndex, Int32 length) 位置 C:\code\taglib-sharp\src\TaglibSharp\ByteVector.cs:行号 439
   在 TagLib.Riff.List.Parse(ByteVector data) 位置 C:\code\taglib-sharp\src\TaglibSharp\Riff\List.cs:行号 612
   在 TagLib.Riff.List..ctor(File file, Int64 position, Int32 length) 位置 C:\code\taglib-sharp\src\TaglibSharp\Riff\List.cs:行号 115
   在 TagLib.Riff.ListTag..ctor(File file, Int64 position, Int32 length) 位置 C:\code\taglib-sharp\src\TaglibSharp\Riff\ListTag.cs:行号 125
   在 TagLib.Riff.InfoTag..ctor(File file, Int64 position, Int32 length) 位置 C:\code\taglib-sharp\src\TaglibSharp\Riff\InfoTag.cs:行号 84
   在 TagLib.Riff.File.Read(Boolean read_tags, ReadStyle style, UInt32& riff_size, Int64& tag_start, Int64& tag_end) 位置 C:\code\taglib-sharp\src\TaglibSharp\Riff\File.cs:行号 523
   在 TagLib.Riff.File..ctor(IFileAbstraction abstraction, ReadStyle propertiesStyle) 位置 C:\code\taglib-sharp\src\TaglibSharp\Riff\File.cs:行号 159   在 TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle) 位置 C:\code\taglib-sharp\src\TaglibSharp\File.cs:行号 1302
   在 ZonyLrcToolsX.Infrastructure.MusicTag.TagLib.MusicInfoLoaderByTagLib.Load(String musicFilePath)
   在 ZonyLrcToolsX.Infrastructure.MusicTag.TagLib.MusicInfoLoaderByTagLib.LoadAsync(String musicFilePath)
   在 ZonyLrcToolsX.Forms.MainForm.<>c__DisplayClass8_0.<<ToolStripButton_SearchMusicFile_Click>b__0>d.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by real-zony** [comment]
@91Metis 该问题同 https://github.com/real-zony/ZonyLrcToolsX/issues/59 重复。
