### ISSUE TITLE
1.0.0.2扫描完报错

### ISSUE THREAD

**Issue by 2023685454** [GameBelial/ZonyLrcToolsX#67]
2020年07月04日 11:03:49 - 产生了异常。
异常提示信息：指定的参数已超出有效值的范围。
参数名: length
异常堆栈信息：   在 TagLib.ByteVector.Mid(Int32 startIndex, Int32 length) 位置 C:\code\taglib-sharp\src\TaglibSharp\ByteVector.cs:行号 439
   在 TagLib.Flac.Picture..ctor(ByteVector data) 位置 C:\code\taglib-sharp\src\TaglibSharp\Flac\Picture.cs:行号 94
   在 TagLib.Flac.Metadata..ctor(IEnumerable`1 blocks) 位置 C:\code\taglib-sharp\src\TaglibSharp\Flac\File.cs:行号 574
   在 TagLib.Flac.File.ReadStart(Int64 start, ReadStyle propertiesStyle) 位置 C:\code\taglib-sharp\src\TaglibSharp\Flac\File.cs:行号 358
   在 TagLib.NonContainer.File.Read(ReadStyle propertiesStyle) 位置 C:\code\taglib-sharp\src\TaglibSharp\NonContainer\File.cs:行号 374
   在 TagLib.Flac.File..ctor(IFileAbstraction abstraction, ReadStyle propertiesStyle) 位置 C:\code\taglib-sharp\src\TaglibSharp\Flac\File.cs:行号 138   在 TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle) 位置 C:\code\taglib-sharp\src\TaglibSharp\File.cs:行号 1302
   在 ZonyLrcToolsX.Infrastructure.MusicTag.TagLib.MusicInfoLoaderByTagLib.Load(String musicFilePath)
   在 ZonyLrcToolsX.Infrastructure.MusicTag.TagLib.MusicInfoLoaderByTagLib.LoadAsync(String musicFilePath)
   在 ZonyLrcToolsX.Forms.MainForm.<>c__DisplayClass8_0.<<ToolStripButton_SearchMusicFile_Click>b__0>d.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

咋办
[exception.log](https://github.com/GameBelial/ZonyLrcToolsX/files/4872042/exception.log)

**Comment by 2023685454** [comment]
怎么解决啊

**Comment by smile-xuc** [comment]
遇到类似问题，期待修复

**Comment by real-zony** [comment]
@smile-xuc 该问题是由于 taglib 引起的，会在 12 日 8 号(0.1.9.6)的版本暂时屏蔽异常解决。
根本原因暂时无法在我这边复现，会在 2.0.0 版本中使用新的 Tag 标签库进行实现尝试解决该问题。

**Comment by real-zony** [comment]
@smile-xuc @2023685454 v4.0.0 preview 采用文件名作为降级策略，可以尝试 4.0.0 版本。
