### ISSUE TITLE
希望能完善文档

### ISSUE THREAD

**Issue by d3vzahvv** [GameBelial/ZonyLrcToolsX#69]
### 迄今为止见到过的最好的歌词下载软件，若是能完善文档将是绝杀

我在使用中遇到了一些小问题，但这并不影响它成为一件优秀的作品
- 在开启**代理**下，无论是**全局**或是**规则**都无法使用，显示下载失败或未找到，这可能与网易云UWP类似，需要关闭代理使用
- 下载完歌词后导入手机发现翻译在歌词后，随后找到插件配置**inline**选项改正即可

希望作者能把它打磨的更好，更便于普通人使用。

**Comment by real-zony** [comment]
感谢你的建议。
