### ISSUE TITLE
下载专辑图片时异常退出问题

### ISSUE THREAD

**Issue by jerrydong1988** [GameBelial/ZonyLrcToolsX#71]
2021年01月30日 21:26:41 - 产生了异常。
异常提示信息：值不能为 null。
参数名: value
异常堆栈信息：   在 Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   在 ZonyLrcToolsX.Downloader.Album.NetEase.NetEaseCloudMusicAlbumDownloader.<DownloadAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 ZonyLrcToolsX.Forms.MainForm.<>c__DisplayClass10_1.<<ToolStripButton_DownloadAlbumImage_Click>b__2>d.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 ZonyLrcToolsX.Infrastructure.TaskWorker.<RunAsync>d__4.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 ZonyLrcToolsX.Forms.MainForm.<ToolStripButton_DownloadAlbumImage_Click>d__10.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by neilyangchn** [comment]
2021年03月03日 17:14:31 - 产生了异常。
异常提示信息：值不能为 null。
参数名: value
异常堆栈信息：   在 Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   在 ZonyLrcToolsX.Downloader.Album.NetEase.NetEaseCloudMusicAlbumDownloader.<DownloadAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 ZonyLrcToolsX.Forms.MainForm.<>c__DisplayClass10_1.<<ToolStripButton_DownloadAlbumImage_Click>b__2>d.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 ZonyLrcToolsX.Infrastructure.TaskWorker.<RunAsync>d__4.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 ZonyLrcToolsX.Forms.MainForm.<ToolStripButton_DownloadAlbumImage_Click>d__10.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by real-zony** [comment]
Close Issue at v4.0.0. prewview.
