### ISSUE TITLE
下载地址失效了

### ISSUE THREAD

**Issue by chainofhonor** [GameBelial/ZonyLrcToolsX#72]
https://github.com/real-zony/ZonyLrcToolsX/releases/download/v0.1.9.1/ZonyLrcToolsX.0.1.9.1.x64.zip
打开0.1.8.0提示更新，然后点确定更新以后浏览器会从这个地址下载压缩包，但是这个地址失效了

**Comment by chainofhonor** [comment]
另外我的中文歌曲目录下有一些歌曲名称在软件里面显示乱码 但是在windows文件夹下查看是正常的中文  请问怎么知道乱码对应的中文是什么 我好改  

比如有一首歌123木头人 在软件里面显示的是123乱码  我对比了一下发现就是123木头人，然后我修改了123木头人这首歌的文件名，操作方式是先把123木头人这几个字复制到txt文本里面，然后再复制这个txt文本，再重命名文件，粘贴 
这样操作以后重新扫描歌曲文件名就正常显示123木头人了

**Comment by real-zony** [comment]
地址已经更新为最新的下载网页。
