### ISSUE TITLE
歌词下载有时与歌曲不对应

### ISSUE THREAD

**Issue by yanph2003** [GameBelial/ZonyLrcToolsX#75]
当下载歌曲信息为
![1](https://user-images.githubusercontent.com/19853316/113885019-10858e00-97f2-11eb-89b0-c9fe2352bfe7.png)
时，从网易云下载歌词为：
![11](https://user-images.githubusercontent.com/19853316/113885026-124f5180-97f2-11eb-9cc5-0e3583202515.png)
经检验为同专辑的
![无标题](https://user-images.githubusercontent.com/19853316/113885043-15e2d880-97f2-11eb-9176-c35e28304d97.png)
的歌词

但欲下载的歌曲存在于网易云音乐，并非因歌曲不存在而导致的误识别

**Comment by yanph2003** [comment]
其他歌曲有时也会出现类似的识别错误

**Comment by real-zony** [comment]
@yanph2003 已解决。
