### ISSUE TITLE
酷狗音乐无法下载翻译歌词

### ISSUE THREAD

**Issue by EricZhou05** [GameBelial/ZonyLrcToolsX#76]
网易云音乐以及QQ音乐都可以下载翻译的歌词但是唯独酷狗音乐歌词只有原文没有翻译。
但是酷狗音乐APP上是显示有翻译的。

**Comment by real-zony** [comment]
目前使用的接口可能没有返回对应的翻译歌词, 具体是哪首歌没有翻译歌词呢?
