### ISSUE TITLE
希望提供歌词选择功能

### ISSUE THREAD

**Issue by zushl** [GameBelial/ZonyLrcToolsX#79]
现在歌词是直接下载歌曲源语言的，外文歌曲就很难看懂，英文还好，日文少数能猜，韩文直接麻瓜，像这种的话能够双语字幕是最好的

**Comment by real-zony** [comment]
重复 Issue [https://github.com/real-zony/ZonyLrcToolsX/issues/87](https://github.com/real-zony/ZonyLrcToolsX/issues/87)，双语歌词功能后续提供。
