### ISSUE TITLE
双击exe无法打开

### ISSUE THREAD

**Issue by WaterSeekingFish** [GameBelial/ZonyLrcToolsX#80]
黑框一闪而过，什么也没发生

**Comment by real-zony** [comment]
Windows 用户请在软件目录当中，按住 Shift + 右键呼出菜单，然后选择 PowerShell (部分用户可能显示的是 命令提示符)，根据下述说明执行命令即可。

macOS 和 Linux 用户请打开终端，切换到软件目录，一样执行命令即可。
