### ISSUE TITLE
无法下载歌词

### ISSUE THREAD

**Issue by trigsoft** [GameBelial/ZonyLrcToolsX#84]
[16:13:03 WRN] 错误代码: 50010，信息: Http 请求的结果反序列化为 Json 失败。
附加信息:
 {"requestParameters":{"csrf_token":"","s":"%e5%a4%aa%e7%a9%ba%e5%bd%88%2b01","offset":0,"type":1,"total":true,"limit":5},"responseString":"{\"result\":\"35b1748964af8a7c1d883e3a6f3c773bb35b675d401af1cf008a9fe84ef5b3d1e2e099d419f4408295890d4dbf40f974418ea6c31b78bbe0d60d0a5744c17881b187bca62263ec471d892608e0c627d987767bb4c0167abca865cabc51d815ee8cf5592b07c1e7dea5c26e1e539c0845f5f7ed85547f4ca86bc29919ff9551f5ca74ec3e63134056e2e0b6d6a0ff04d81f2cd84edd0d08fdb73d4007c9642610ff839cdecbabe8c5e278561a2065af334a94aba2328f74557941d2c2ab06d9bc4bb210e3bb5314b99ad30d727c83bad716eda77bd9ff2dc4ac097438ba048afd454906109548457b7a723d893a3b12e89685399f5f2ebbf28d31ee52eb1832b1484e10465ea668694332c8622c891647ecb6e28147870298de7485c63284fe05122b3dbf6248cfb1254d4abe4daf7314e248b1cd549a0d046ad325209cb5ec6d5b1e2e6275bf4256e7ca9c7825d2e9b38b73a8545185f77ff0628578b1ae9e95eda8cabf8559a7850414fc91d740b14e0bd521ab9be2061a7222e2b7cae8bc496b10c295b34f3820e895b52ae2e72a00afd32a647ea2308f64ab3823876f1f06d85f7e28158e4fd2db1be71afb4b0046af8e8c99a32af7f7eef10efb46f4aafc7bfd7c75b5ba65a6455ed3998dbbdbd612321f85e89f6d2ebb74bee09781751fbc7545ec00b72ea77de04ad1348bafb24a39d9a3a04dd81914894908b36240327f6666bf2f7362f62e178e77972f6437d6f1e6a540a179cfaa36b1f40111b30a9ac1f93311f6d21583dd7fa610df012f3450062dde32c618057f7f48155662628b46bcb6638004f1be166ed3013b0b047687ef39132d9ea740041187e0a24fa3897fd86901f1f9c9dca1ea0e1064128a658515ed64ebbbf2951472728505a895af3300ae42106a3c1257336262fd2da54748340df640f79a8504e01544d6443eb0b18bb4a2f443a3a1891712ebdec9ec33740defc12f89c06d1580ea1a39630981045f7444f6f4b51ac9df46f147cbf69649856192a84143b25cc3204d30b366ec85de3011e4c71204dd0c09342effbcd35dff17bad306a83a57b77ba6660b127dc1dde6a2b5bb0e7d22eabcbf44188bc9a0a0442ea8abc99ff0a40206f504fb8c7c3410e0c1c96d1fcda00d2ac866f57c0591e6f3961a8a0d26f108a50e4004b2ff31b2630a57b77aec9e36fdf85740721fe240aaedaa9d057f38afbbeaf1fb74f5e30ecb488395caab01d9dd59efa4477553bf816b9709ae15c1e6779d33cd80b3e4bfabd93757fafc59e347a8fba47a77ab3d773a55c8a2838977817b219c20bf44062d48ca09148aae8dd98b35407ca746f0f143e2bec8a2ef193b6be0f5f5b1963629add1cc60e79c7e22ed343baaf3b2a3a520236d2be53a8348b62d10856e8510c334433e0740ddbaadafe3f5eae310ea7ce76265142991b94f9ebc3c04fb2ef16321b49645c1992cdd2f2ae4aaa8f1de6ae2bfc181b20ddd7fcad67f8595c9e08597a70704bc1e2f79749ca472a0104647d84236651fc699abcc9adaf1fb74f5823816981404afb0f4c3dd2225077c4b4dbf9385e384ae3fb127427829ae8d8079c5304905d2903a213ccaedd3be9813f72b8cbb3fcaa4d96a9e37cd219c20bfd699e9c9cf6325e2bf92d9d6e33a47a019657c6b7b00d667beed6b8b40dd1a48454881cb49f221fd0469242a2069104e5d1aa265db7f0ead9cd94f75df9d854fcd993031cfde7c486e9820372dd2dc0e21198b2f89aebc96cf3b9c3ed535fdd9ff2d0a74c78338e78c52ecb729b2383a83a2b73137a7498a57724819a3a34840ffb5a8dfd7a3a7a3cba82da5dbbba17955b5bef663305dcd13b5094d476fb1b88348cc9a7bd6ec92d9e778e8120f30daafebbbd158d3a1c7e910d9617f1f72566921719e06ae3e62dd7f53a518d2f51721c3eb2b89a54533c9f5991e7e22ebe800a6e76523b325c9d9cb0813fb1a4ea353b14fee8932480bf5e61e5b23fd878256dde775d2a065929e2582a5b5bc073d6c9fca591a15c09a5108169498b39900437eb8e6b345e5b0ed7cd0cbe97729a7b096e099b2562546de02124bf0898ebee8234f818a72ebd7c084ca4f300addeb5b1a6aac330489d908ae3705f2df9d10dc7de3bb9f5240388c699c172ae88c797ccf9b169f324862e7adf31a5984f8ad92b63af143bf248e415f52445f4968a032c579e015a212ee8c40a2183c45545fea948e27162cb2e6f542995fc28c01b9bccfa368e9578b7b38d676db7b384712af104d3cc7911fc749689b0b3540340e15c120b6e9de8536edb3e2a2773da132bc772de87d03d0562f2df6b2ccc809531d20497f9e623aa60308bf34aada35e6b098a3d164a5c3b2a072c7136589bf9526a8ba843ac51af681bfcb124ab50e3c5050493a835f837655cb87b1748baef4c93b0622f71057ffb029365faf59f585fd10ac7cfd7dbd2e5873cfa3963ed3543eed4d902f046b3c48b6a8fd726fdb10929c90e004c73a76e99cf18504cc3e9b483b0067b3654b19a6d2076bd27287f27838404dd54d2329224da47ffd6620a710815229e8c840077fcaaff9a72d325e90d0a3920440776f4426a6743eb24f4f2dd06d23da4a176b12c012560464489c50917c64d578aaf3da8288a4724948b5c20990133476cb8c1949ed8d36256dd9906b91dcdd490879cb000fd74f4d133ab7333149467fc9a85796ecf7dede4918e798bf51d5bfaa89d99f29bbee3a180d768a0029bb6459f5a8212a39da02eff2ad72dbcdc5fcebe882af3e6414d5a6872f632314bc2a9ed6b2c6bc3017723118a0719464abca74181806020a176a9d1aeecbcbb1df22a13821623ebe648a333299325a3a04daaab439d63c3337a71001ed8be2c3ecb697684d9294e4169cd3e0d6f46d784e5231b553ec0aa84e66e3071072abec3467290713042faaf5794ebe99f1f94cb589775f4df71685d3a52e044800427b25e8c9f5344eec62f2057cc1b3d795a69bb4e88526492daf79d8ba4010462976f692893a651f53ac313cd580c5e443ab2f3aa7e98c94f663206310f69c2eb483dda0b03ef2d03768732c98c02f385f126ad3661a6d06f5a2eabca83a10dc9993e76b547f796804536207f94862ecc320d58e438c68155b0ef57471bbb9153c3ecd95e650d76bae7262b6997fcb30837c43c192ecb6f6d8d6a7bee08171834e617b8fbc9a94171ac03339ea5bc05d3789f2189559b2906bdb22d3609187cf1a65f401bc9b98b2b79c3aa5b5d8499455e46448c519c34afc37362addb06000f4ff9316cf0c0cc3f2a6531f83908e4bdf6176a6217f38b55b34803274e9f7d8b8dd8321d2076b075fb5af1a07e9b2169d3881a062cdf456660485ecd7d14200c1785885a0eb99a44595b4c2f110b0b4cfde22e37f470df6725e85e63da84143312f1b7b4dd488abc36dc8d2621e620799e8cadeb23a6f32191a5fab45f28de2f443a3048514060013376a48a7100d6d902cf689174453d708f26db31c5cf1e7e2ae0db4141eba1385568b24334eddc84e4d3de9d16e14fd739dc7c84b3cd45bc1e7de040101ec0098e8449cdd263aefa12a7e2968bb6264d20ea062ad264ddad3ae39fac20cc8ed067c74385398efff4c4bdffcc97910200edf921746d3f2a3ba9159dd95211e636bddbcb5f9c8b1a4e8ed223a40fd2db310138574ed8554518eaeafb148d9a0fb104745a80e5f729abc481d9e181710bbfb9e6d1622a7452d4e1d45200955a1a86647d36d9e445d3be7b21101f4cf3baf5f09ae9a211f32bcdb676f07ba98f6662e6238a579459c6b53a32859a14bf5a6830f44ca1fc8dedda384bbe0123d6a773bc0dc961a7ed766bc2f9fe2bf06a8aa76c836578cc5f19f4736b6f681c2a71007ffaf3e9a41e61eadde50cd04fcf4d6a56162bcc2a42e37af26e8c0b5dbff2a1196bcc93736e7f4cf1a6889778ad60f0ea8e2b3ff047c11515f5dd81304c8e6f1a749aa995ba41069d0a35b04a7bff4d68596ec85973ee84881347973cd502d9dfd57133b4e79648390171883a1d84818a8c1af47bcfe4801113b093660ce7fc5395baaf55985f66632738974dae84732f5fd66124f0a8bdd0a8583929e834acae87ee88d9a015aa7a8adc54e8a3295ada2a1db5bec76a78957e099e192a06656a6909932ee1a3d9ba5bc39046b30144fb38bff7ccb635c080511046be9bac7d98bfb46d9104090e489297e9e899a4e70137c8b59400307631956373a98a0b38e852ea86295d109d949d0503981fd210b11a9322cb8d3e50a75ac00808dd4e75112420bbc374885aa74d23298decc1e8d163cae6bde795e040183dad2adafcadd2daa21426d9ccbc548d908dabeb148a804fb73ba217d0479bcae0029d29d629dfd62133b97cb74b1a7e9896b2272b874ece83baebd0ae2c4d033504377c81ef5d2a0de74411a5941a6c171c5db8906770408a709d61e62ee84deaea276703dcd6696f1160aef7c1de28da2aaf6ea81428db4816a50129ec028e03d51198b16e8c1a005fbdcc7214049a7897a76b0bb9a8aa9ba48f906857bd934368aa7d899c7b35ea8b8ed33e4d07918acdb4a2adda4c209b0f39b01c608674d86867774f1e706d15f42d7bc40483a03747232a6caccd2beb6338d3a051e5804016e29b8adb3ca26de30b6fd38f92ca83af45666c562bc55d1bf656d593a0414ec124d45a8cba2c61885454ddda0d2eb222c0f857f95d8da30e21a94390fc0bb7472899977f1c7bac7bb2fdada5bd36a0d2cc57c9256d15454663369435379bb349f3338a548e2f9af29d596c7cbad50a0775938ea85a78d03a4071087d6a33c042c8965e79cba774bdf6620ea518974d9f5f5450a9232c175525d81a332300101cf4daf3ed5676629b0a700133a69d9e0809ee01ef5aed2e08540f66dd84d1a0a4c18484226ca20ddf9482d481d0136d7b3943a539f3cc0208e45a24dca5789a0fc2249aa763642660a71bb0a57415133beca95a13079f1046d9c229ea308c227de6b8d5604a070e92078eda61dddac76b729001727671ee49da3e319cd42c54f7a65190384fe\",\"code\":200,\"abroad\":true}"}
[16:13:03 INF] 歌词数据下载完成，成功: 10 失败0。

**Comment by real-zony** [comment]
@trigsoft 目前无法复现该问题，能否上传问题歌曲文件？

**Comment by real-zony** [comment]
长时间没有得到回复，如果有任何问题请重新 reopen 这个 issue。
