### ISSUE TITLE
报错，好像是调用了没实例化的对象

### ISSUE THREAD

**Issue by DancingSnow0517** [GameBelial/ZonyLrcToolsX#85]
![image](https://user-images.githubusercontent.com/60736156/154200049-9e732045-0daf-40cc-868b-8b66163f3bb5.png)

**Comment by real-zony** [comment]
@DancingSnow0517 你好，你能提供这首歌曲的原始文件吗？
![image](https://user-images.githubusercontent.com/3907132/159009451-539f8289-5c5b-4ff4-877e-9bacf71ec325.png)

看起来跟这个问题有点相似。https://github.com/real-zony/ZonyLrcToolsX/issues/88

**Comment by real-zony** [comment]
@DancingSnow0517 如果最新版本还有问题，请重新打开此 Issue。
