### ISSUE TITLE
双语歌词

### ISSUE THREAD

**Issue by CiaoBye** [GameBelial/ZonyLrcToolsX#87]
希望可以下载到双语歌词啊~

**Comment by real-zony** [comment]
问题已在 [ZonyLrcToolsX_Alpha.2022032001](https://github.com/real-zony/ZonyLrcToolsX/milestone/6) 解决，将会在 3 月 20 日发布。

**Comment by CiaoBye** [comment]
多谢 到时候会立马更新的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "real-zony/ZonyLrcToolsX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月19日(星期六) 中午12:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [real-zony/ZonyLrcToolsX] 双语歌词 (Issue #87)





 
问题已在 ZonyLrcToolsX_Alpha.2022032001 解决，将会在 3 月 20 日发布。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
