### ISSUE TITLE
dsf格式扫描报错

### ISSUE THREAD

**Issue by jerrydong1988** [GameBelial/ZonyLrcToolsX#88]
![image](https://user-images.githubusercontent.com/17478939/158936801-5d5c47d8-9ca0-4326-9138-c5b4d07825df.png)

**Comment by jerrydong1988** [comment]
另外一个未知异常
![image](https://user-images.githubusercontent.com/17478939/158937081-3403946e-a460-405c-bab0-1d77a8c2c880.png)

**Comment by real-zony** [comment]
@jerrydong1988  你能提供这个歌曲源文件供我测试吗？
![image](https://user-images.githubusercontent.com/3907132/159009135-b692c489-9824-4c33-9254-d3bac20cb4ed.png)

**Comment by real-zony** [comment]
请使用最新版本再试一下，关于第一个问题，只需要在 `config.yaml` 里面添加上 dsf 后缀即可。
如果最新版本还有问题，请重新打开此 Issue。

![image](https://user-images.githubusercontent.com/3907132/159146113-88568df0-b643-4a16-a69f-5c1b7dae5d9a.png)

**Comment by jerrydong1988** [comment]
歌曲源文件再G盘里
 茫茫草原.wav
<https://drive.google.com/file/d/1euSk6xDw-jrWeRqOjlD1-u-ZlU3JWfX1/view?usp=drive_web>


Zony ***@***.***> 于2022年3月18日周五 21:13写道：
