### ISSUE TITLE
下载发生错误但最后输出失败0

### ISSUE THREAD

**Issue by MasterOfStar** [GameBelial/ZonyLrcToolsX#89]
![image](https://user-images.githubusercontent.com/21274896/159475027-ea302a97-75e5-4a84-80c3-6b46fb0bfd1e.png)
如图，下载发生错误但最后输出失败0 但打开文件夹缺少出错部分曲目的歌词

**Comment by real-zony** [comment]
因为代码里面没有对失败进行计数，后续会把这个功能实装。
