### ISSUE TITLE
是否可以先读取歌曲的元数据如果没有元数据再根据文件名？

### ISSUE THREAD

**Issue by shelken** [GameBelial/ZonyLrcToolsX#96]
是否可以先读取歌曲的元数据如果没有元数据再根据文件名？因为我是先把元数据都整理好的，然后当时命名的时候只有歌曲名（musicBrainZ的默认命名规则），所以希望加个策略，先读取元数据信息，没有才以文件名，这样会准确点？

**Comment by real-zony** [comment]
该问题新版本已经解决，等待 Release，参考 [https://github.com/real-zony/ZonyLrcToolsX/issues/92](https://github.com/real-zony/ZonyLrcToolsX/issues/92).
